Update change-site-address.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2285
Opened 2020-08-24 21:45 UTC by WayneEwington

Document that Site Rename is unsupported if the publishing feature been activated or has been previously activated.

2020-08-25 03:29 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-08-25 07:25 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/change-site-address.md
> +>[!NOTE]
```suggestion
> [!NOTE]
```

2020-08-25 07:26 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/change-site-address.md
> +>If the Publishing Feature has been activated or has been previously activated in the site, then performing a Site Rename is unsupported.
```suggestion
> If the Publishing feature has been activated or has been previously activated in the site, then performing a Site Rename is unsupported.
```

2020-08-25 07:27 UTC, JohanFreelancer9 requested changes
Copy review.

2020-08-26 18:14 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-03 15:59 UTC, merged