Adding link to more info about Classic WF retirement
MicrosoftDocs/OfficeDocs-SharePoint pull request #2297
Opened 2020-09-01 17:24 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2269

2020-09-03 23:57 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-04 02:42 UTC, JohanFreelancer9 commented on migration/sp-teams-sites-migration-guide.md
>  >[!Note]
```suggestion
> [!NOTE]
```

2020-09-04 02:43 UTC, JohanFreelancer9 commented on migration/sp-teams-sites-migration-guide.md
> +>Classic workflow will be supported and available until 2026. We recommend taking this into consideration as you plan for your workflow lifetime. For more information, please see [SharePoint 2010 wor
```suggestion
> Classic workflow will be supported and available until 2026. We recommend taking this into consideration as you plan for your workflow lifetime. For more information, please see [SharePoint 2010 workflow retirement](https://support.microsoft.com/office/sharepoint-2010-workflow-retirement-1ca3fff8-9985-410a-85aa-8120f626965f).
```

2020-09-04 02:47 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-04 15:22 UTC, JohanFreelancer9 approved these changes

2020-09-08 04:26 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-18 23:50 UTC, get-itips commented
@JoanneHendrickson Can you kindly review and merge? Thanks!

2020-09-24 17:59 UTC, get-itips commented
@JoanneHendrickson can you kindly review? Thanks

2020-10-22 13:53 UTC, merged