Resolve syncing conflicts from repo_sync_working_branch to live
MicrosoftDocs/OfficeDocs-SharePoint pull request #2300
Opened 2020-09-02 23:01 UTC by openpublishbuild

Pull request opened by Docs to resolve syncing conflicts from repo_sync_working_branch to live.

2020-09-03 23:57 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-04 01:51 UTC, JohanFreelancer9 commented on OneDrive/plan-onedrive-enterprise.md
> +After you download the app, you can create a script in Configuration Manager by following the process in [Create and run PowerShell scripts from the Configuration Manager Console](/configmgr/apps/dep
```suggestion
After you have downloaded the app, you can create a script in Configuration Manager by following the process in [Create and run PowerShell scripts from the Configuration Manager Console](/configmgr/apps/deploy-use/create-deploy-scripts/) or by using a traditional script-based application such as that in [Create applications in Configuration Manager](/configmgr/apps/deploy-use/create-applications/). When using either option, the command to update the OneDrive sync app using the installer is:
```

2020-09-04 01:58 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +#### If you already have M365 learning pathways 4.0 - provision the SharePoint Success Site from the look book
```suggestion
#### If you already have Microsoft 365 learning pathways 4.0 - provision the SharePoint success site from the look book
```

2020-09-04 01:59 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +If you already have Learning Pathways 4.0 or greater provisioned on your tenant, you can provision Learning Pathways from the SharePoint Look book site. Make sure you have met the requirements as cov
```suggestion
If you already have learning pathways 4.0 or greater provisioned on your tenant, you can provision learning pathways from the SharePoint look book site. Make sure you have met the requirements as covered earlier in this documentation. 
```

2020-09-04 02:01 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +1. Go to the [look book]( https://provisioning-test.sharepointpnp.com/details/0b860749-56a0-4c4c-992c-536d56d9accf) and select **Add to your tenant**
```suggestion
1. Go to the [look book](https://provisioning-test.sharepointpnp.com/details/0b860749-56a0-4c4c-992c-536d56d9accf) and select **Add to your tenant**
```

2020-09-04 02:02 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +5. Next, navigate to your tenant's Learning Pathways site
```suggestion
5. Next, navigate to your tenant's learning pathways site
```

2020-09-04 02:04 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +11. To confirm M365 learning pathways has been successfully provisioned, go to the SharePoint site you provisioned, select **Get Started > Plan your site.** You should see the web part on the page as
```suggestion
11. To confirm that  Microsoft 365 learning pathways has been successfully provisioned, go to the SharePoint site you provisioned, select **Get Started > Plan your site.** You should see the web part on the page as shown in the following image: 
```

2020-09-04 02:05 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
>  If you **don’t already have** M365 learning pathways installed in your tenant, follow these instructions:
```suggestion
If you **don’t already have** Microsoft 365 learning pathways installed in your tenant, follow these instructions:
```

2020-09-04 02:06 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +### Provision the SharePoint Success Site to your tenant from the Learning pathways administrative page
```suggestion
### Provision the SharePoint success site to your tenant from the learning pathways administrative page
```

2020-09-04 02:07 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +After you have successfully provisioned for the first time or updated M365 learning pathways, you are ready to provision the SharePoint Success Site.
```suggestion
After you have successfully provisioned for the first time or updated Microsoft 365 learning pathways, you are ready to provision the SharePoint success site.
```

2020-09-04 02:08 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
>  3. Navigate to the location of the site using the URL supplied by your tenant administrator or select SharePoint from the Office 365 Home page, and then select the M365 learning pathways site.
```suggestion
3. Navigate to the location of the site using the URL supplied by your tenant administrator or select SharePoint from the Office 365 Home page, and then select the Microsoft 365 learning pathways site.
```

2020-09-04 02:09 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +4. From the learning pathways Home menu, select **Learning Pathways Administration.**
```suggestion
4. From the learning pathways Home menu, select **Learning Pathways Administration**.
```

2020-09-04 02:10 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +5. Select the … (ellipses) and then select **Add Content Pack.**
```suggestion
5. Select the … (ellipses) and then select **Add Content Pack**.
```

2020-09-04 02:11 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +6. Select SharePoint Success Site to open the SharePoint Success Site provisioning page.
```suggestion
6. Select **SharePoint Success Site** to open the SharePoint success site provisioning page. 
```

2020-09-04 02:11 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +7. Select **Add to your tenant.**
```suggestion
7. Select **Add to your tenant**.
```

2020-09-04 02:13 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +8. Fill out the details and then select **Provision.**
```suggestion
8. Fill out the details and then select **Provision**.
```

2020-09-04 02:13 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +9. Select **Confirm.**
```suggestion
9. Select **Confirm**.
```

2020-09-04 02:14 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +10. When you see Provisioning completed, select the **CustomLearningAdministration** tab as shown in the following image.
```suggestion
10. When you see **Provisioning completed**, select the **CustomLearningAdministration** tab as shown in the following image.
```

2020-09-04 02:15 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +12. To confirm M365 learning pathways has been successfully provisioned, go to the SharePoint site you provisioned, select **Get Started > Plan your site.** You should see the web part on the page as
```suggestion
12. To confirm that Microsoft 365 learning pathways has been successfully provisioned, go to the SharePoint site you provisioned, select **Get Started > Plan your site**. You should see the web part on the page as shown in the following image: 
```

2020-09-04 02:21 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +2. Fill out the email and URL address sections and  and select **Provision**
```suggestion
2. Fill out the email and URL address sections and select **Provision**.
```

2020-09-04 02:22 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +> Enter this address in the URL field - https://microsoft.github.io/customlearning_staging/learningpathways/
```suggestion
> Enter this address in the URL field - https://microsoft.github.io/customlearning_staging/learningpathways/.
```

2020-09-04 02:22 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +3. Select **Confirm**
```suggestion
3. Select **Confirm**.
```

2020-09-04 02:24 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +6. Select **Home > Learning Pathways Administration**
```suggestion
6. Select **Home** > **Learning Pathways Administration**.
```

2020-09-04 02:24 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +7. Select the **…** (ellipse), then select **Add to Content Pack**
```suggestion
7. Select the **…** (ellipse), then select **Add to Content Pack**.
```

2020-09-04 02:25 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +8. Select **SharePoint Success Site**
```suggestion
8. Select **SharePoint Success Site**.
```

2020-09-04 02:25 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +9. You will see the SharePoint look book site appear in a new tab. You can close this tab and select the **CustomLearning Administration tab**
```suggestion
9. You will see the SharePoint look book site appear in a new tab. You can close this tab and select the **CustomLearning Administration tab**.
```

2020-09-04 02:27 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
> +1. Go to the [M365 learning pathways solution page](https://provisioning-test.sharepointpnp.com/details/29f8646c-f754-4a8b-9b33-e09d55e29f67)
```suggestion
1. Go to the [M365 learning pathways solution page](https://provisioning-test.sharepointpnp.com/details/29f8646c-f754-4a8b-9b33-e09d55e29f67).
```

2020-09-04 02:27 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss.md
>  10. When the update is complete, select **Close**
```suggestion
10. When the update is complete, select **Close**.
```

2020-09-04 02:32 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-05 03:11 UTC, JohanFreelancer9 commented on migration/mover-plan-migration.md
> +> Need help? [Open a support request here](https://support.microsoft.com/supportforbusiness/productselection?sapId=c3fa6eba-e1f0-0715-4519-94a9740c5f2c)
```suggestion
> Need help? [Open a support request here](https://support.microsoft.com/supportforbusiness/productselection?sapId=c3fa6eba-e1f0-0715-4519-94a9740c5f2c).
```

2020-09-14 02:11 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/customize-sss.md
> +If you’re not sure your tenant has the site, contact your SharePoint tenant administrator to verify that the SharePoint Success Site been provisioned and ask for the M365 learning pathways and ShareP
```suggestion
If you’re not sure your tenant has the site, contact your SharePoint tenant administrator to verify that the SharePoint Success Site has been provisioned and ask for the M365 learning pathways and SharePoint Success Site URLs. If you are the tenant administrator and M365 learning pathways has not been provisioned, see the provisioning guidance.
```

2020-09-14 02:14 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/customize-sss.md
> +Select which content to display in your SharePoint Success Site by [hiding and showing](https://docs.microsoft.com/office365/customlearning/custom_hideshowsub) subcategories of content. For example,
```suggestion
Select which content to display in your SharePoint Success Site by [hiding and showing](https://docs.microsoft.com/office365/customlearning/custom_hideshowsub) subcategories of content. For example, if you don’t want users to have access to advanced site creation, you can hide that subcategory so that it won't be visible to users. Decide which content is appropriate for the purpose of your SharePoint Success Site. 
```

2020-09-14 02:19 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/customize-sss.md
> +**2. People web part** - Edit the [People web part](https://support.microsoft.com/office/show-people-profiles-on-your-page-with-the-people-web-part-7e52c5f6-2d72-48fa-a9d3-d2750765fa05) to display co
```suggestion
**2. People web part** - Edit the [People web part](https://support.microsoft.com/office/show-people-profiles-on-your-page-with-the-people-web-part-7e52c5f6-2d72-48fa-a9d3-d2750765fa05) to display contact information so new site owners can reach out for help.
```

2020-09-14 02:28 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/customize-sss.md
> +- Build culture and community by integrating a [Yammer web part](https://support.microsoft.com/office/use-a-yammer-web-part-in-sharepoint-online-a53cfa0c-3d09-42c8-a286-1038a81c59da#conversations).
```suggestion
- Build culture and community by integrating a [Yammer web part](https://support.microsoft.com/office/use-a-yammer-web-part-in-sharepoint-online-a53cfa0c-3d09-42c8-a286-1038a81c59da#conversations)
```

2020-09-14 02:29 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/customize-sss.md
> +To help build, grow, and sustain your SharePoint adoption efforts, its recommended to [create a SharePoint user group community in Yammer](https://support.microsoft.com/office/create-a-group-in-yamme
```suggestion
To help build, grow, and sustain your SharePoint adoption efforts, it's recommended to [create a SharePoint user group community in Yammer](https://support.microsoft.com/office/create-a-group-in-yammer-b407af4f-9a58-4b12-b43e-afbb1b07c889).  Your SharePoint champions and power users can answer SharePoint related questions posted in the Yammer group and encourage site owners to share their successes and best practices. See the [champions guidance](https://docs.microsoft.com/office365/customlearning/champ_findthem) for more information on how to identify and build a successful champions program. To increase visibility and engagement within your portal champions community, integrate the Yammer group hosting your community into the SharePoint Success Site using the [Yammer conversations web part](https://support.microsoft.com/office/use-a-yammer-web-part-in-sharepoint-online-a53cfa0c-3d09-42c8-a286-1038a81c59da).
```

2020-09-14 02:30 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/customize-sss.md
> +To help build, grow, and sustain your SharePoint adoption efforts, its recommended to [create a SharePoint user group community in Yammer](https://support.microsoft.com/office/create-a-group-in-yamme
Please change "its" in the first line to "it's".

2020-09-14 02:40 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-lock-status.md
> +    > If you installed a previous version of the SharePoint Online Management Shell, go to Add or remove programs and uninstall "SharePoint Online Management Shell." <br>On the Download Center page,
```suggestion
    > If you installed a previous version of the SharePoint Online Management Shell, go to Add or remove programs and uninstall "SharePoint Online Management Shell." <br>On the Download Center page, select your language and then click the Download button. You'll be asked to choose between downloading a x64 and x86 .msi file. Download the x64 file if you're running the 64-bit version of Windows or the x86 file if you're running the 32-bit version. If you don't know, see [Which version of Windows operating system am I running?](https://support.microsoft.com/help/13443/windows-which-operating-system) After the file has downloaded, run it and follow the steps in the Setup Wizard.
```

2020-09-14 02:42 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-lock-status.md
> +    > If you installed a previous version of the SharePoint Online Management Shell, go to Add or remove programs and uninstall "SharePoint Online Management Shell." <br>On the Download Center page,
Please remove the period (.) before the last sentence and edit the last sentence as indicated

2020-09-14 02:44 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-lock-status.md
> +3. At the PowerShell command prompt, type the following command, and then press ENTER.
```suggestion
3. At the PowerShell command prompt, type the following command, and then press **ENTER**:
```

2020-09-14 02:59 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/customize-sss.md
> +## Share the site with end-users
```suggestion
## Share the site with end users
```

2020-09-14 03:00 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss-lookbook.md
> +Once you’ve confirm the person provisioning and the tenant being provsioned meet the following prerequisites, you are ready to provision:
```suggestion
Once you’ve confirmed the person provisioning and the tenant being provisioned meet the following prerequisites, you are ready to provision:
```

2020-09-14 03:02 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss-lookbook.md
> +If you already have Learning Pathways 4.0 or greater provisioned on your tenant, you can provision Learning Pathways from the SharePoint Look book site.
```suggestion
If you already have Learning Pathways 4.0 or greater provisioned on your tenant, you can provision Learning Pathways from the SharePoint look book site. 
```

2020-09-14 03:03 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/provision-sss-lookbook.md
> +7.	Select the … (ellipse), then select **Add to Content Pack**
```suggestion
7.	Select the **…** (ellipse), then select **Add to Content Pack**
```

2020-09-14 03:21 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +After a agent is configured, anyone with the permission to go into the SharePoint Admin center can create tasks. The tasks will be automatically distributed to one of the configured agents.
```suggestion
After an agent is configured, anyone with the permission to go into the SharePoint Admin center can create tasks. The tasks will be automatically distributed to one of the configured agents.
```

2020-09-14 03:22 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +3. Select Add Task.
```suggestion
3. Select **Add Task**.
```

2020-09-14 03:22 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +4. Add a source
```suggestion
4. Add a source.
```

2020-09-14 03:22 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +5. Add a destination
```suggestion
5. Add a destination.
```

2020-09-14 03:23 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +6.
```suggestion
```

2020-09-14 03:26 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +7. Enter your SharePoint admin username and password. These are to the SharePoint environment where you will be migrating your content. Select **Next**.
```suggestion
6. Enter your SharePoint admin username and password. These are to the SharePoint environment where you will be migrating your content. Select **Next**.
```

2020-09-14 03:26 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +8. Enter your Windows credentials that will provide access to **all** the file shares that contain the content you want to migrate. Select **Install**.
```suggestion
7. Enter your Windows credentials that will provide access to **all** the file shares that contain the content you want to migrate. Select **Install**.
```

2020-09-14 03:27 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +9. Test agent access (optional) or click **Close**.
```suggestion
8. Test agent access (optional) or select **Close**.
```

2020-09-14 03:27 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +On completion this computer will be added to the available agents that the Migration Manager can assign tasks.
```suggestion
On completion, this computer will be added to the available agents to which the Migration Manager can assign tasks.
```

2020-09-14 03:28 UTC, JohanFreelancer9 commented on migration/mm-create-task.md
> +>[!Important]
```suggestion
> [!IMPORTANT]
```

2020-09-14 03:30 UTC, JohanFreelancer9 commented on migration/mover-error-faq.md
> +|General: How to stop and restart a migration after recovering from an error...	|Check the box on the left of an User Transfer Row and then click "Start Migrating x User" this will create an incremen
```suggestion
|General: How to stop and restart a migration after recovering from an error...	|Check the box on the left of a User Transfer Row and then select **Start Migrating x User**. This will create an incremental transfer to pick up where you left off.|
```

2020-09-14 03:34 UTC, JohanFreelancer9 commented on migration/mover-release-notes.md
> +-	Enforce that authorizing user is Office365 Global Admin or SharePoint Admin when authorizing a connector
```suggestion
-	Enforce that the authorizing user is Office365 Global Admin or SharePoint Admin when authorizing a connector.
```

2020-09-14 03:35 UTC, JohanFreelancer9 commented on migration/mover-release-notes.md
> +-	Transfers going into some Office 365 sites may fail to move certain folders if the sites have the SharePoint Online option `ThicketSupportDisabled` set to `false`. To correct this issue, customers
```suggestion
-	Transfers going into some Office 365 sites may fail to move certain folders if the sites have the SharePoint Online option `ThicketSupportDisabled` set to `false`. To correct this issue, customers can set `ThicketSupportDisabled` to `true` in the SharePoint Online sites experiencing the issues. Alternatively, they can contact Mover support to apply a workaround to their transfers. The workaround consists of automatically appending an underscore (_) to the folder names. The folders that may fail due to this SharePoint Online option have names ending in:
```

2020-09-14 03:36 UTC, JohanFreelancer9 commented on migration/mover-release-notes.md
> +-	Transfers going into some Office 365 sites may fail to move certain folders if the sites have the SharePoint Online option `ThicketSupportDisabled` set to `false`. To correct this issue, customers
Please change "consists in" to "consists of" in the last line.

2020-09-14 03:37 UTC, JohanFreelancer9 commented on migration/mover-release-notes.md
> +>[!Note]
```suggestion
> [!NOTE]
```

2020-09-14 03:38 UTC, JohanFreelancer9 commented on migration/mover-release-notes.md
> +>The workaround should NOT be requested if the SPO option `ThicketSupportDisabled` has been set to `true` as this may cause data duplication.
```suggestion
> The workaround should _not_ be requested if the SPO option `ThicketSupportDisabled` has been set to `true`, as this may cause data duplication.
```

2020-09-14 03:43 UTC, JohanFreelancer9 commented on migration/mover-reports.md
> +|Success|	Displays all successful Data and Files transferred.|
```suggestion
|Success|	Displays all successful data and files transferred.|
```

2020-09-14 03:44 UTC, JohanFreelancer9 commented on migration/mover-reports.md
> +|Success|	Displays all successful Data and Files transferred.|
```suggestion
|Success|	Displays all successful data and files transferred.|
```

2020-09-14 03:44 UTC, JohanFreelancer9 commented on migration/mover-reports.md
>  |Failed	|Displays all Data and Files that have failed to transfer.|
```suggestion
|Failed	|Displays all data and files that have failed to transfer.|
```

2020-09-14 03:55 UTC, JohanFreelancer9 commented on migration/mover-reports.md
> +|Last Data Velocity (Bytes/hour)|Data (bytes) transferred, divided by the total duration for the last run.|
```suggestion
|Last Data Velocity (bytes/hour)|Data (bytes) transferred, divided by the total duration for the last run.|
```

2020-09-14 03:57 UTC, JohanFreelancer9 commented on migration/mover-transfer-status-codes.md
> +When a transaction ends, it may be automatically re-run. But this will only happen when ALL of the following conditions are met:
```suggestion
When a transaction ends, it may be automatically rerun. But this will only happen when _all_ of the following conditions are met:
```

2020-09-14 03:59 UTC, JohanFreelancer9 commented on migration/mover-transfer-status-codes.md
> +    - If we first scan a task, it may trigger re-runs. If then we migrate the task, it may also trigger re-runs.
```suggestion
    - If we first scan a task, it may trigger reruns. If we then migrate the task, it may also trigger reruns.
```

2020-09-14 04:01 UTC, JohanFreelancer9 commented on migration/mover-transfer-status-codes.md
> +    - If we started scanning a task and then cancelled it. And then we started scanning the task again, it will NOT trigger re-runs because it was not the first time the task was scanned
```suggestion
    - If we started scanning a task and canceled it, and then started scanning the task again, it will _not_ trigger reruns because it was not the first time the task was scanned.
```

2020-09-14 04:04 UTC, JohanFreelancer9 commented on migration/mover-transfer-status-codes.md
> +- **We haven’t run out of automatic re-runs.** A task will be automatically re-run a maximum of 3 times. A first scan/migrate action on a task may result in triggering a total of four transactions: t
```suggestion
- **We haven’t run out of automatic reruns.** A task will be automatically rerun a maximum of three times. A first scan/migrate action on a task may result in triggering a total of four transactions: the original transaction (run), and the three additional attempts (reruns). Six reruns can be triggered at most; three for the initial scan, and three for the initial migration.
```

2020-09-14 04:08 UTC, JohanFreelancer9 commented on migration/sharepoint-online-and-onedrive-migration-speed.md
>  **Question: My migration is blocked with consistent high volume of Http 503 errors ("Server Too Busy") ?**</br>
```suggestion
**Question: My migration is blocked with consistent high volume of Http 503 errors ("Server Too Busy")**</br>
```

2020-09-14 04:09 UTC, JohanFreelancer9 commented on migration/sharepoint-online-and-onedrive-migration-speed.md
>  1. Navigate to https://admin.microsoft.com
```suggestion
1. Navigate to https://admin.microsoft.com.
```

2020-09-14 04:09 UTC, JohanFreelancer9 commented on migration/sharepoint-online-and-onedrive-migration-speed.md
>  >[!Note]
```suggestion
>[!NOTE]
```

2020-09-14 04:10 UTC, JohanFreelancer9 commented on migration/sharepoint-online-and-onedrive-migration-speed.md
>  >If you are using the old M365 admin center you can skip step 8 as the "Description" field will not exist.
```suggestion
> If you are using the old M365 admin center you can skip step 8 as the "Description" field will not exist.
```

2020-09-14 04:11 UTC, JohanFreelancer9 commented on migration/sharepoint-online-and-onedrive-migration-speed.md
>      - Estimate the number of throttles (for example, x throttle per hour?) and when (specific time and date) did the throttling happened.
```suggestion
    - Estimate the number of throttles (for example, x throttle per hour?) and when (specific time and date) did the throttling happen.
```

2020-09-14 04:14 UTC, JohanFreelancer9 commented on migration/sp-teams-sites-migration-guide.md
> +# SharePoint Server team sites Migration Guide
```suggestion
# SharePoint Server teams sites Migration Guide
```

2020-09-14 04:17 UTC, JohanFreelancer9 commented on migration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets.md
> +>  The **SharePoint Migration Tool** (SPMT) helps simplify your migration process. SPMT provides a wizard-like experience to guide you through the process of migrating either your SharePoint Server t
```suggestion
>  The **SharePoint Migration Tool** (SPMT) helps simplify your migration process. SPMT provides a wizard-like experience to guide you through the process of migrating either your SharePoint Server team sites or your network file shares to Microsoft 365. It is available to all Microsoft 365 users. > To download the tool, go to [SharePoint Migration Tool](https://spmtreleasescus.blob.core.windows.net/install/default.htm).
```

2020-09-14 04:17 UTC, JohanFreelancer9 commented on migration/sp-teams-sites-migration-guide.md
>  This guide will help you prepare to migrate from SharePoint Server teams sites to SharePoint in Microsoft 365.
```suggestion
This guide will help you prepare to migrate from SharePoint Server team sites to SharePoint in Microsoft 365.
```

2020-09-14 04:24 UTC, JohanFreelancer9 requested changes
Copy review - some additional edits please (mainly to new content).

2020-09-16 23:02 UTC, merged