Update use-silent-account-configuration.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2319
Opened 2020-09-11 20:58 UTC by BillSproule

Clarifications and additional verification steps and warning about sysprep.

2020-09-14 05:23 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-14 06:10 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +> See [Verify SilentAccountConfig](use-silent-account-configuration.md#VerifySilentAccountConfig) section below to verify and troubleshoot your configuration.
```suggestion
> See the [Verify SilentAccountConfig](use-silent-account-configuration.md#VerifySilentAccountConfig) section below to verify and troubleshoot your configuration.
```

2020-09-14 06:14 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +## Windows Image Prep Requirements
```suggestion
## Windows Image Prep requirements
```

2020-09-14 06:16 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +SilentAccountConfig creates a SilentBusinessConfigCompleted registry entry once SilentAccountConfig has successfully provisioned the user in OneDrive.exe.  This prevents SilentAccountConfig from re-p
```suggestion
SilentAccountConfig creates a SilentBusinessConfigCompleted registry entry once SilentAccountConfig has successfully provisioned the user in OneDrive.exe. This prevents SilentAccountConfig from reprovisioning the user in OneDrive.exe if the user manually stops syncing.
```

2020-09-14 06:17 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +If SilentAccountConfig has successfully completed on a machine your going use as your master for building a Windows deployment image (ie SysPrep), you need to ensure this registry key is removed befo
```suggestion
If SilentAccountConfig has successfully completed on a machine you're going to use as your master for building a Windows deployment image (i.e. SysPrep), you need to ensure this registry key is removed before you prepare your image. You can do so by running the following command:
```

2020-09-14 06:34 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +3. Set the Silent Config policy registry entry (must be run from an Administrator cmd window)
```suggestion
3. Set the Silent Config policy registry entry (must be run from an administrator CMD window)
```

2020-09-14 06:35 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +1. Unlink all pre-existing Business instances in OneDrive
```suggestion
1. Unlink all pre-existing Business instances in OneDrive.
```

2020-09-14 06:35 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +2. Clear the registry of any previous successful Silent Business Config runs
```suggestion
2. Clear the registry of any previous successful Silent Business Config runs.
```

2020-09-14 06:36 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +4. Sign out of Windows (Ctrl+Alt+Delete Sign Out)
```suggestion
4. Sign out of Windows (Ctrl+Alt+Delete Sign Out).
```

2020-09-14 06:37 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +5. Sign into Windows
```suggestion
5. Sign into Windows.
```

2020-09-14 06:38 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +6. Shortly you should see a blue cloud tray icon.  Clicking on the blue cloud tray icon should show the activity center pop-up showing ongoing/recent activity from the first sync.  If so, SilentAccou
```suggestion
6. Shortly you should see a blue cloud tray icon. Clicking on the blue cloud tray icon should show the activity center pop-up showing ongoing/recent activity from the first sync. If so, SilentAccountConfig has worked correctly.
```

2020-09-14 06:40 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +7. If instead you see the "Set up OneDrive" first run wizard dialog, SilentAccountConfig was unable to silently sign in or failed for another reason. Verify you have completed these steps correctly b
```suggestion
7. If instead, you see the "Set up OneDrive" first run wizard dialog, SilentAccountConfig was unable to silently sign in or failed for another reason. Verify you have completed these steps correctly by repeating them again. Perform the [Verify Single Sign On (SSO)](use-silent-account-configuration.md#VerifySSO) steps below to confirm that SSO is not a problem. Gather sync client logs to send to the engineering team for further help.
```

2020-09-14 06:41 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +1. Ensure you can manually get the OneDrive sync client to sync content with your on premises SharePoint 2019 Server before proceeding.  See [Configure sync app for syncing with SharePoint Server](/s
```suggestion
1. Ensure you can manually get the OneDrive sync client to sync content with your on-premises SharePoint 2019 Server before proceeding. See [Configure sync app for syncing with SharePoint Server](/sharepoint/install/new-onedrive-sync-client) for details.
```

2020-09-14 06:43 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +2. Set the SharePointOnPremPrioritization reg key value to 1 (This will ensure on-prem takes precedence over SPO, deleting the regkey to revert to SPO)
```suggestion
2. Set the SharePointOnPremPrioritization reg key value to 1 (this will ensure on-premises takes precedence over SPO, deleting the reg key to revert to SPO).
```

2020-09-14 06:43 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +3. Follow steps 1 through 6 in above SPO instructions.
```suggestion
3. Follow steps 1 through 6 in SPO instructions above.
```

2020-09-14 06:45 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +4. If instead you see the "Set up OneDrive" first run wizard dialog, SilentAccountConfig was unable to silently sign in or failed for another reason.  Verify you have completed these steps correctly
```suggestion
4. If instead, you see the "Set up OneDrive" first run wizard dialog, SilentAccountConfig was unable to silently sign in or failed for another reason. Verify you have completed these steps correctly by repeating them again. Gather sync client logs to send to the engineering team for further help.
```

2020-09-14 06:50 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +## Verify Single Sign On (SSO) is working
```suggestion
## Verify that Single Sign On (SSO) is working
```

2020-09-14 06:51 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +The most common reason for SilentAccountConfig to fail is the credentials are not available to OneDrive.exe without user interaction.  Proceed with these instructions to determine if this is a proble
```suggestion
The most common reason for SilentAccountConfig to fail is the credentials are not available to OneDrive.exe without user interaction. Proceed with these instructions to determine if this is a problem in your case.
```

2020-09-14 06:53 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +If you have a machine you think should work with SilentAccountConfig you can manually verify SSO (single sign on) is working correctly to ensure the environment is configured correctly.
```suggestion
If you have a machine you think should work with SilentAccountConfig you can manually verify that SSO is working correctly to ensure that the environment is configured correctly. 
```

2020-09-14 06:54 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +2. Shut down any running OneDrive.exe processes (verify in Task Manager Details tab - Ctrl+Shift+Esc).
```suggestion
2. Shut down any running OneDrive.exe processes (verify in the Task Manager Details tab - Ctrl+Shift+Esc).
```

2020-09-14 06:55 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +3. Start menu - OneDrive, you should see the "Set up OneDrive" dialog (if not unlink/stop syncing any business accounts and start over).
```suggestion
3. In the OneDrive Start menu, you should see the "Set up OneDrive" dialog (if not, unlink/stop syncing any business accounts and start over).
```

2020-09-14 06:56 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +4. Enter the same email address the user signed into Windows with (try alias@domain and domain\alias forms).
```suggestion
4. Enter the same email address that the user used to sign into Windows (try alias@domain and domain\alias forms).
```

2020-09-14 06:57 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +6. The dialog should switch to a “signing in” page with a spinning icon for a few seconds.  It should then proceed to the next part of the wizard without asking for a password.
```suggestion
6. The dialog should switch to a “signing in” page with a spinning icon for a few seconds. It should then proceed to the next part of the wizard without asking for a password.
```

2020-09-14 07:00 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +8. If you do see a password prompt the environment is not configured properly for silent sign on (SSO).  This could be due to a problem with how the machine is domain joined (eg a trust relationship
```suggestion
8. If you do see a password prompt, the environment is not configured properly for silent sign on.  This could be due to a problem with how the machine is domain joined (for example, a trust relationship problem), a problem with ADFS configuration, an AAD CA policy requiring user interaction, you didn't provide the same user email address as the one used to sign into Windows, or some other reason.  You will need to resolve whatever is blocking silent sign on before SilentAccountConfig will work for you.
```

2020-09-14 07:00 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +9. Remove the EnableADAL key you added in step 1
```suggestion
9. Remove the EnableADAL key you added in step 1:
```

2020-09-14 07:04 UTC, JohanFreelancer9 commented on OneDrive/use-silent-account-configuration.md
> +Note when using SilentAccountConfig, you do not need to specify EnableADAL=1.  This is only necessary when manually testing SSO in the above steps where we manually sign in (instead of using SilentAc
```suggestion
> [!NOTE]
> When using SilentAccountConfig, you do not need to specify EnableADAL=1.  This is only necessary when manually testing SSO in the above steps where we manually sign in (instead of using SilentAccountConfig to sign in).  However, if you want users who manually set up OneDrive sync to benefit from SSO to minimize how often they need to enter a password in sync, you can deploy the EnableADAL key on your users' computers.
```

2020-09-14 07:07 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-14 19:22 UTC, BillSproule commented on OneDrive/use-silent-account-configuration.md
> +3. Start menu - OneDrive, you should see the "Set up OneDrive" dialog (if not unlink/stop syncing any business accounts and start over).
This edit changes the meaning.  Its the Windows Start Menu that needs to be opened, then OneDrive needs to be clicked/selected

2020-09-15 04:58 UTC, JohanFreelancer9 approved these changes

2020-09-17 00:15 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-09-21 20:56 UTC, merged