updating with new KFM silent policy changes
MicrosoftDocs/OfficeDocs-SharePoint pull request #2331
Opened 2020-09-18 00:42 UTC by cartergreen

- we support files that aren't selected for sync in the silent policy, we will just force sync those libraries 
- we support folder selection in the silent policy

2020-09-18 00:43 UTC, cartergreen commented
@kaarins @gacarini

2020-09-18 01:19 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-18 03:45 UTC, JohanFreelancer9 commented on OneDrive/redirect-known-folders.md
> +    Use this setting to redirect and move known folders to OneDrive without any user interaction. Move all the folders or select the desired individual folders.  After a folder is moved, the policy w
```suggestion
    Use this setting to redirect and move known folders to OneDrive without any user interaction. Move all the folders or select the desired individual folders. After a folder is moved, the policy will not affect the folder again, even if the selection for the folder changes. 
```

2020-09-18 03:47 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2020-09-19 03:33 UTC, JohanFreelancer9 approved these changes

2020-09-21 21:09 UTC, merged