Clarifying for other language
MicrosoftDocs/OfficeDocs-SharePoint pull request #2339
Opened 2020-09-22 15:41 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2299

2020-09-23 02:45 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-23 04:20 UTC, JohanFreelancer9 commented on migration/how-to-format-your-csv-file-for-data-content-migration.md
> +> If you use the standard out-of-the-box Document library ("Shared Documents"), you must use the internal name "Documents" as the placeholder value for the  *Source Document Library* (Column B) in yo
```suggestion
> If you use the standard out-of-the-box Document library ("Shared Documents"), you must use the internal name "Documents" as the placeholder value for the *Source Document Library* (Column B) in your CSV file. If you enter "Shared Documents" in that column, you will receive an "invalid document library" error.
```

2020-09-23 04:22 UTC, JohanFreelancer9 commented on migration/how-to-format-your-csv-file-for-data-content-migration.md
> +> If the language of the destination SharePoint site is other than english, check the internal name of the "Shared Documents" Document library by browsing to https://contoso.sharepoint.com/sites/Samp
```suggestion
> If the language of the destination SharePoint site is other than English, check the internal name of the "Shared Documents" Document library by browsing to https://contoso.sharepoint.com/sites/SampleSite/_layouts/15/viewlsts.aspx?view=14.
```

2020-09-23 04:25 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-23 14:14 UTC, JohanFreelancer9 approved these changes

2020-09-28 04:30 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-22 13:50 UTC, merged