Update manage-query-suggestions.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2341
Opened 2020-09-24 17:09 UTC by colevode

Updating the documentation to reflect the latest SLA and features of the query suggestions pipeline.

2020-09-28 04:30 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-28 08:13 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-query-suggestions.md
> +You can edit a list of query suggestions that you've manually created. To edit a list that you've already imported in to SharePoint, choose **Export to text file**, update the text file with your cha
```suggestion
You can edit a list of query suggestions that you've manually created. To edit a list that you've already imported into SharePoint, choose **Export to text file**, update the text file with your changes, and then re-import it. After you've uploaded your query suggestions file, it might take up to a week until your query suggestions are displayed. You can check that they're working properly by entering a phrase from your list of query suggestions in the search box. The query suggestion should appear below the search box.
```

2020-09-28 08:14 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-query-suggestions.md
> +You can edit a list of query suggestions that you've manually created. To edit a list that you've already imported in to SharePoint, choose **Export to text file**, update the text file with your cha
Please change "in to" to "into" in the first line.

2020-09-28 08:15 UTC, JohanFreelancer9 requested changes
Copy review - one additional edit.

2020-09-30 02:33 UTC, scanum commented
@arnekv PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-25 22:33 UTC, merged