Update migrate-onenote-spmt.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2344
Opened 2020-09-24 19:22 UTC by baardhermansen

Removed surplus HTML line breaks.
Corrected markdown for Important.

2020-09-28 04:30 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-28 08:08 UTC, JohanFreelancer9 commented on migration/migrate-onenote-spmt.md
>  We recommend that you migrate with this setting set to **On**. The files will migrate as a OneNote notebook.  You can open the notebooks with the OneNote application or via Microsoft Teams by manuall
```suggestion
We recommend that you migrate with this setting set to **On**. The files will migrate as a OneNote notebook. You can open the notebooks with the OneNote application or via Microsoft Teams by manually adding a tab to Teams.
```

2020-09-28 08:09 UTC, JohanFreelancer9 commented on migration/migrate-onenote-spmt.md
>  Before you migrate your files, decide how you want your OneNote folders to appear. In **Settings**, go to **Migrate OneNote folders as OneNote notebook**.  The default setting is **Off**.
```suggestion
Before you migrate your files, decide how you want your OneNote folders to appear. In **Settings**, go to **Migrate OneNote folders as OneNote notebook**. The default setting is **Off**.
```

2020-09-28 08:09 UTC, JohanFreelancer9 commented on migration/migrate-onenote-spmt.md
>  If you choose to migrate with the setting set to **Off**, your OneNote folders will migrate as a normal folder with files that you can navigate just as you can any other folder.  It will appear in Sh
```suggestion
If you choose to migrate with the setting set to **Off**, your OneNote folders will migrate as a normal folder with files that you can navigate just as you can any other folder. It will appear in SharePoint like this:
```

2020-09-28 08:09 UTC, JohanFreelancer9 requested changes
Copy review - a few additional edits, please.

2020-09-28 12:22 UTC, baardhermansen commented on migration/migrate-onenote-spmt.md
>  Before you migrate your files, decide how you want your OneNote folders to appear. In **Settings**, go to **Migrate OneNote folders as OneNote notebook**.  The default setting is **Off**.
How did i miss that one...

2020-09-28 14:08 UTC, JohanFreelancer9 approved these changes

2020-09-30 02:33 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-22 13:50 UTC, merged