Update Fileshare-to-ODSP-migration-guide.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2346
Opened 2020-09-25 01:33 UTC by baardhermansen

Minor formatting changes.

2020-09-28 04:30 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-28 07:34 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
>  If you're working on a file or folder intended for team consumption and collaboration, move it to a **shared library** where team members have access by default. OneDrive gives you access to all your
```suggestion
If you're working on a file or folder intended for team consumption and collaboration, move it to a **shared library** where team members have access by default. OneDrive gives you access to all your shared libraries in Microsoft Teams, SharePoint, or Outlook. When you need a new shared library for team files, you can create one right from OneDrive, add members, and start working together.
```

2020-09-28 07:34 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
> +Most migrations fall into regular phases as follows.  Proven success factors for migration include planning, assessing and remediating, preparing your target environment, migrating and onboarding you
```suggestion
Most migrations fall into regular phases as follows. Proven success factors for migration include planning, assessing and remediating, preparing your target environment, migrating, and onboarding your users.
```

2020-09-28 07:36 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
> +The SharePoint Migration Tool (SPMT) provides the ability to scan your files and provide assessment reports . To find any issues with your file before migration, turn on the setting **Only perform sc
```suggestion
The SharePoint Migration Tool (SPMT) provides the ability to scan your files and provide assessment reports. To find any issues with your file before migration, turn on the setting **Only perform scanning**.
```

2020-09-28 07:38 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
>  |**File extensions**|Find all files in the Folders and Files report whose Path ends in one of the extensions defined here: [Types of files that cannot be added to a list or library](https://support.o
```suggestion
|**File extensions**|Find all files in the Folders and Files report whose Path ends in one of the extensions defined here: [Types of files that cannot be added to a list or library](https://support.office.com/article/30BE234D-E551-4C2A-8DE8-F8546FFBF5B3)|If the blocked file types are scripting files, they are blocked because scripting capabilities are turned off by default in OneDrive. <br><br>If you want to allow these file types, turn on scripting capabilities as described here: [Allow or prevent custom script](/sharepoint/allow-or-prevent-custom-script). <br><br>Make sure you understand why these files are blocked by default as described here: [Security considerations of allowing custom script](/sharepoint/security-considerations-of-allowing-custom-script).|
```

2020-09-28 07:38 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
>  |**File and folder name characters**|Find all items in the Folders and Files report whose name contains any of the characters detailed here: [Invalid file names and file types in OneDrive and SharePo
```suggestion
|**File and folder name characters**|Find all items in the Folders and Files report whose name contains any of the characters detailed here: [Invalid file names and file types in OneDrive and SharePoint](https://support.office.com/article/64883a5d-228e-48f5-b3d2-eb39e07630fa)|Work with your migration vendor to substitute these characters in all file and folder names.<br><br>**Note:** The # and % characters are supported but not enabled by default. Follow these steps to enable them: [New support for # and % in SharePoint and OneDrive](https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/New-support-for-and-in-SharePoint-Online-and-OneDrive-for/ba-p/60357).|
```

2020-09-28 07:45 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
>  |**File extensions**|Find all files in the Folders and Files report whose Path ends in one of the extensions defined here: [Types of files that cannot be added to a list or library](https://support.o
Please add period (.) after the link.

2020-09-28 07:46 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
>  |**File and folder name characters**|Find all items in the Folders and Files report whose name contains any of the characters detailed here: [Invalid file names and file types in OneDrive and SharePo
Please add period after the last link.

2020-09-28 07:52 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
> +FastTrack is a Microsoft service included in your subscription cost offering you with a set of best practices, tools, resources, and experts committed to making your experience with the Microsoft Clo
```suggestion
FastTrack is a Microsoft service included in your subscription cost providing you with a set of best practices, tools, resources, and experts committed to making your experience with the Microsoft cloud a great one. OneDrive onboarding guidance, migration benefits, and adoption guidance are included in the benefit offering.
```

2020-09-28 07:57 UTC, JohanFreelancer9 requested changes
Copy review.

2020-09-28 14:06 UTC, JohanFreelancer9 approved these changes

2020-09-30 02:34 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-21 18:05 UTC, merged