Rewrite article that describes how to implement federated authentication between SPS and AD FS
MicrosoftDocs/OfficeDocs-SharePoint pull request #2349
Opened 2020-09-25 09:24 UTC by Yvand

Current version of [this article](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server) has many issues:
- It does not describe the configuration needed/expected on AD FS
- It contains a lot of unnecessary text
- The whole SharePoint configuration is completely wrong and confusing. I'll just highlights a few points:
	- It adds multiple certificates SPTrustedRootAuthority, some of which are totally useless
	- The script that creates the SPTrustedIdentityTokenIssuer is very confusing and has a lot of readability and practical issues
	- It misses the configuration of the web application, the IIS site and the creation of the site collection, while it contains unnecessary/irrelevant chapters (on tracing and audiences)

I preferred to rewrite it entirely to create a clear step by step to configure federated authentication end to end, including AD FS. I used an approach very similar to [this article](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-integrate-with-sharepoint-server) that I rewrote a few years ago.

2020-09-28 04:30 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-09-28 06:54 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md
> +- An AD FS farm version 2 or newer, already created, with the public key of the ADFS signing certificate exported in a .cer file
```suggestion
- An AD FS farm version 2 or newer, already created, with the public key of the AD FS signing certificate exported in a .cer file.
```

2020-09-28 07:01 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md
> +- If the ADFS signing certificate is issued by a certificate authority (best practice for security reasons)
```suggestion
- If the AD FS signing certificate is issued by a certificate authority (best practice for security reasons)
```

2020-09-28 07:05 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md
> +        # URL of the SharePoint site federated with ADFS
```suggestion
        # URL of the SharePoint site federated with AD FS
```

2020-09-28 07:09 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md
> +In this step, you create a team site collection with 2 administrators: One as a Windows administrator and one as a federated (AD FS) administrator.
```suggestion
In this step, you create a team site collection with two administrators: One as a Windows administrator and one as a federated (AD FS) administrator.
```

2020-09-28 07:18 UTC, JohanFreelancer9 requested changes
Copy review - a few minor edits.

2020-09-28 08:22 UTC, JohanFreelancer9 approved these changes

2020-09-30 08:31 UTC, Yvand commented
@scanum what are the next steps for this PR?

2020-10-02 12:44 UTC, Yvand commented
@scanum can you follow up this PR ?

2020-10-05 04:30 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-05 12:39 UTC, MikePlumleyMSFT commented
@SerdarSoysal

2020-10-14 08:39 UTC, Yvand commented
@SerdarSoysal any update on this?

2020-10-28 21:21 UTC, merged