corrections to Connect to Box -- misspellings, missing words, formatting
MicrosoftDocs/OfficeDocs-SharePoint pull request #2391
Opened 2020-10-25 22:49 UTC by ReQ6W7rFnaBxyfb

If this PR is accepted, please label it as "hacktoberfest-accepted" or classify the repository with the "hacktoberfest" topic. Thanks! 
https://hacktoberfest.digitalocean.com/hacktoberfest-update

2020-10-26 04:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-26 06:44 UTC, JohanFreelancer9 commented on migration/mm-box-connection.md
>  1. From the [Migration page in the new SharePoint admin center](https://admin.microsoft.com/sharepoint?page=migrationCenter&modern) and select Box "Get started".
```suggestion
1. From the [Migration page in the new SharePoint admin center](https://admin.microsoft.com/sharepoint?page=migrationCenter&modern), select the **Get started** box.
```

2020-10-26 06:46 UTC, JohanFreelancer9 commented on migration/mm-box-connection.md
>  1. From the [Migration page in the new SharePoint admin center](https://admin.microsoft.com/sharepoint?page=migrationCenter&modern) and select Box "Get started".
```suggestion
1. From the [Migration page in the new SharePoint admin center](https://admin.microsoft.com/sharepoint?page=migrationCenter&modern), select Box "Get started".
```

2020-10-26 06:48 UTC, JohanFreelancer9 commented on migration/mm-box-connection.md
> +3. Mover works in the background to scan Box, and copy data to the Microsoft 365.  Authorize Mover with your Microsoft credentials to connect your co-admin Box account. Click **Authorize Mover**.
```suggestion
3. Mover works in the background to scan Box and to copy data to Microsoft 365.  Authorize Mover with your Microsoft credentials to connect your co-admin Box account. Select **Authorize Mover**.
```

2020-10-26 06:50 UTC, JohanFreelancer9 commented on migration/mm-box-connection.md
> +9. In the Box screen -- click "Authorize new app".
```suggestion
9. In the Box screen, select "Authorize new app".
```

2020-10-26 06:51 UTC, JohanFreelancer9 commented on migration/mm-box-connection.md
> +10. Paste in the client ID you copied from the earlier screen. Enter the client id for application for which you would like to grant access.
```suggestion
10. Paste in the client ID you copied from the earlier screen. Enter the client id for the application for which you would like to grant access.
```

2020-10-26 06:53 UTC, JohanFreelancer9 commented on migration/mm-box-connection.md
> +11. An App Authorization page appears and lists the authorization details of the request. Click "Authorize".
```suggestion
11. An App Authorization page appears and lists the authorization details of the request. Select "Authorize".
```

2020-10-26 06:54 UTC, JohanFreelancer9 commented on migration/mm-box-connection.md
>  12. You are now connected to Box. Click Finish to close window.
```suggestion
12. You are now connected to Box. Select **Finish** to close the window.
```

2020-10-26 06:58 UTC, JohanFreelancer9 commented on migration/mm-box-connection.md
> +6. Log in to grant access to Box. Click **Authorize.**
```suggestion
6. Log in to grant access to Box. Select **Authorize.**
```

2020-10-26 06:59 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-27 05:30 UTC, JohanFreelancer9 approved these changes

2020-10-28 04:22 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-10-30 22:16 UTC, merged

2020-10-30 22:28 UTC, JoanneHendrickson commented
This was published in error. Deleting.