fixed misspellings
MicrosoftDocs/OfficeDocs-SharePoint pull request #2392
Opened 2020-10-25 23:12 UTC by ReQ6W7rFnaBxyfb

If this PR is accepted, please label it as "hacktoberfest-accepted" or classify the repository with the "hacktoberfest" topic. Thanks! 
https://hacktoberfest.digitalocean.com/hacktoberfest-update

2020-10-26 04:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-26 05:32 UTC, JohanFreelancer9 commented on OneDrive/deploy-on-windows.md
> +You will need Client Side Object Model (CSOM) knowledge if you want to automate querying the team site to determine the appropriate siteId, webId and listId to build the appropriate URL.
```suggestion
You will need Client Side Object Model (CSOM) knowledge if you want to automate querying the team site to determine the appropriate siteId, webId, and listId to build the appropriate URL. 
```

2020-10-26 05:36 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/deprecation-of-site-mailboxes.md
>    > - The site mailboxes contain special folder named, "Documents", of type IPF.ShortcutFolder. This contains "links" to files that are on SP site. The actual SP files must be       exported using eD
```suggestion
  > - The site mailboxes contain a special folder named, "Documents", of type IPF.ShortcutFolder. This contains "links" to files that are on SP sites. The actual SP files must be exported using eDiscovery for SP sites.
```

2020-10-26 06:03 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/deprecation-of-site-mailboxes.md
>    > - Folder with no email items inside them will not be exported.
```suggestion
  > - Folders with no email items inside them will not be exported.
```

2020-10-26 06:05 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/deprecation-of-site-mailboxes.md
>    > - The document attachments in the emails of Documents folder are just place holder, the actual documents are stored in SharePoint.
```suggestion
  > - The document attachments in the emails of Documents folders are just placeholders, the actual documents are stored in SharePoint.
```

2020-10-26 06:06 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/deprecation-of-site-mailboxes.md
>  > - Folder with no email items inside them will not be exported.
```suggestion
> - Folders with no email items inside them will not be exported.
```

2020-10-26 06:07 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/deprecation-of-site-mailboxes.md
>  > - The site mailboxes contain special folder named, "Documents", of type IPF.ShortcutFolder. This contains "links" to files that are on SP site. The actual SP files must be       exported using eDis
```suggestion
> - The site mailboxes contain a special folder named, "Documents", of type IPF.ShortcutFolder. This contains "links" to files that are on SP sites. The actual SP files must be exported using eDiscovery for SP sites.
```

2020-10-26 06:08 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/deprecation-of-site-mailboxes.md
>  > - The document attachments in the emails of Documents folder are just place holder, the actual documents are stored in SharePoint.
```suggestion
> - The document attachments in the emails of Documents folders are just placeholders, the actual documents are stored in SharePoint.
```

2020-10-26 06:15 UTC, JohanFreelancer9 commented on migration/mm-settings.md
> +|Do not migrate files with these extensions|Enter a list of file extensions of file types you do not want to migrate. Separate each extension entered with a colon. Do not include the dot.  Example: T
```suggestion
|Do not migrate files with these extensions|Enter a list of file extensions of file types you do not want to migrate. Separate each extension entered with a colon. Do not include the dot.  Example: TXT:EXE:JPEG: </br> **Note**: For files with multiple file extensions, for example .ext1.ext2, add only the last extension, ext2, to the exclusion list.|
```

2020-10-26 06:17 UTC, JohanFreelancer9 commented on migration/mm-settings.md
>  |Migrate OneNote folder as OneNote notebook <br/>|By default, this is set to **Off**. When set to **Off**, OneNote folders it will display as a regular folder in SharePoint.  If set to **On** the mig
```suggestion
|Migrate OneNote folder as OneNote notebook <br/>|By default, this is set to **Off**. When set to **Off**, OneNote folders it will display as a regular folder in SharePoint.  If set to **On**, the migrated notebook folder will display as a OneNote link in SharePoint.<br/>|
```

2020-10-26 06:26 UTC, JohanFreelancer9 commented on migration/mover-running-migration.md
>  - Select all user(s). At the top of navigation bar, select the checkbox.
```suggestion
- Select all users. At the top of the navigation bar, select the checkbox.
```

2020-10-26 06:30 UTC, JohanFreelancer9 commented on migration/using-the-sharepoint-migration-tool-reports.md
>  |Message  <br/> |more detailed Error or informational message generated.  <br/> |
```suggestion
|Message  <br/> |More detailed error or informational message generated.  <br/> |```

2020-10-26 06:31 UTC, JohanFreelancer9 commented on migration/using-the-sharepoint-migration-tool-reports.md
>  |Incremental Round  <br/> |The round number added to the end of the report name (RO, R1, etc.) indicates if the scan or job has been rerun.  <br/> |
```suggestion
|Incremental round  <br/> |The round number added to the end of the report name (RO, R1, etc.) indicates if the scan or job has been rerun.  <br/> |
```

2020-10-26 06:40 UTC, JohanFreelancer9 requested changes
Copy review - @ReQ6W7rFnaBxyfb a few additional edits, please.

2020-10-27 05:28 UTC, JohanFreelancer9 approved these changes

2020-11-09 17:44 UTC, merged