Update line 29, according to https://office.visualstudio.com/OC/_work…
MicrosoftDocs/OfficeDocs-SharePoint pull request #2394
Opened 2020-10-26 02:29 UTC by fishgwo

Update line 29, according to https://office.visualstudio.com/OC/_workitems/edit/4554929

2020-10-26 04:17 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-10-26 05:29 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/organization-assets-library.md
> +- **Office templates**. When a user selects to create a new Office file (from Office.com or the Word, Excel, or PowerPoint desktop app), the user can select the tab for your organization to see the t
```suggestion
- **Office templates**. When a user selects to create a new Office file (from Office.com or the Word, Excel, or PowerPoint desktop app), the user can select the tab for your organization to see the templates. (Currently, this feature is only available for PowerPoint on Office.com and users need to be assigned a license to Office 365 E3 or E5. The templates aren't available from the New menu. To create a doc from a template, go to Office.com > app start page > Office Template Library.)
```

2020-10-26 05:29 UTC, JohanFreelancer9 requested changes
Copy review.

2020-10-28 04:22 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-11-02 02:24 UTC, fishgwo commented
@kaarins  Is there progress on this, can we release document update?

2020-11-02 22:38 UTC, kaarins commented
Thank you! I made additional updates after discussing with PM and product marketing.

2020-11-02 22:38 UTC, closed without merging