Tweaks to policy that excludes files from being uploaded
MicrosoftDocs/OfficeDocs-SharePoint pull request #2463
Opened 2020-11-24 18:42 UTC by gacarini

2020-11-25 05:34 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-11-25 06:03 UTC, JohanFreelancer9 commented on OneDrive/use-group-policy.md
> +Enabling this policy creates a list of strings under the follow following path HKLM\SOFTWARE\Policies\Microsoft\OneDrive\EnableODIgnoreListFromGPO.
```suggestion
Enabling this policy creates a list of strings under the following path: HKLM\SOFTWARE\Policies\Microsoft\OneDrive\EnableODIgnoreListFromGPO.
```

2020-11-25 06:04 UTC, JohanFreelancer9 commented on OneDrive/use-group-policy.md
> +> This setting does not support excluding Office files from being uploaded. All other file types are supported.
```suggestion
> This setting does not support excluding Office files from being uploaded. Excluding all other file types are supported.
```

2020-11-25 06:04 UTC, JohanFreelancer9 requested changes
Copy review.

2020-11-26 19:34 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-03 23:58 UTC, merged