Update information-barriers.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2500
Opened 2020-12-17 02:06 UTC by nibandyo

Adding updates to the SharePoint information barrier article per discussion with @kaarins

2020-12-21 04:27 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2020-12-21 08:56 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/information-barriers.md
> +With SharePoint information barriers, a SharePoint or global admin can associate segments to a site to prevent the site from being shared with or accessed by users outside the segments. Up to 100 com
```suggestion
With SharePoint information barriers, a SharePoint or global admin can associate segments to a site to prevent the site from being shared with or accessed by users outside the segments. Up to 100 compatible segments can be associated with a site. The segments are associated at the site level (previously called site collection level). Microsoft 365 groups connected to the site is also associated with the site's segment.
```

2020-12-21 08:58 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/information-barriers.md
> +- [Complete the form](https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR_mCQfArPllNo4NRhexFZxRUNEZCTTZLVVJHOEJOVVlCTUdJNDVERko5Qy4u) to enable SharePoint and OneDrive inform
```suggestion
- [Complete the form](https://forms.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR_mCQfArPllNo4NRhexFZxRUNEZCTTZLVVJHOEJOVVlCTUdJNDVERko5Qy4u) to enable SharePoint and OneDrive information barriers in your organization. Please note that SharePoint and OneDrive information barriers can only be enabled in your tenant if you already have at least one active information barriers policy. 
```

2020-12-21 09:03 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-26 02:53 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2020-12-26 04:46 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/information-barriers.md
> +- After SharePoint and OneDrive information barriers is enabled in your tenant, wait 24 hours for the changes to propagate through your environment.
```suggestion
- After SharePoint and OneDrive information barriers are enabled in your tenant, wait 24 hours for the changes to propagate through your environment. 
```

2021-01-06 03:26 UTC, merged