Update network-utilization-planning.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2520
Opened 2020-12-31 22:05 UTC by ChenyingYang

1. Operational sync: Update to reflect on benefit of differential sync; Link to updated KFM page; Note/callout on allow WNS traffic. 
2. Use OneDrive Group Policy objects: Add LEDBAT GPO.

2021-01-03 05:37 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-03 10:24 UTC, JohanFreelancer9 commented on OneDrive/network-utilization-planning.md
> +> Windows Notification Service or WNS plays an important role in efficient network utilization. Instead of sync client constantly pulling to check for remote changes, WNS ensures that any changes fro
Please confirm that the last sentence (Work with your network team to make sure proxies: Allow network traffic to bypass *.wns.windows.com; Avoid HTTPS decryption for *.wns.windows.com.) is correct. I am sure there is something missing.

2021-01-03 10:24 UTC, JohanFreelancer9 commented on OneDrive/network-utilization-planning.md
> +A spike in upload traffic is expected if you deploy the Known Folder Move setting in your organization. If your organization is large and your users have a lot of files in their known folders, make s
```suggestion
A spike in upload traffic is expected if you deploy the Known Folder Move setting in your organization. If your organization is large and your users have a lot of files in their known folders, make sure you roll out the Group Policy objects slowly to minimize the network impact of uploading files. For detailed deployment guidance on Known Folder Move, see [Redirect and move Windows known folders to OneDrive](https://docs.microsoft.com/onedrive/redirect-known-folders).
```

2021-01-03 10:25 UTC, JohanFreelancer9 commented on OneDrive/network-utilization-planning.md
> +A spike in upload traffic is expected if you deploy the Known Folder Move setting in your organization. If your organization is large and your users have a lot of files in their known folders, make s
Please remove the locale from the link.

2021-01-03 10:27 UTC, JohanFreelancer9 requested changes
Copy review.

2021-01-05 02:06 UTC, ChenyingYang commented on OneDrive/network-utilization-planning.md
> +> Windows Notification Service or WNS plays an important role in efficient network utilization. Instead of sync client constantly pulling to check for remote changes, WNS ensures that any changes fro
This guidance is directly copied from https://docs.microsoft.com/en-us/onedrive/ideal-state-configuration#windows-notification-service. Instead of putting them in one sentence, how about separating them just like the ones linked.

2021-01-05 02:45 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-01-05 03:17 UTC, JohanFreelancer9 commented on OneDrive/network-utilization-planning.md
> +> Windows Notification Service or WNS plays an important role in efficient network utilization. Instead of sync client constantly pulling to check for remote changes, WNS ensures that any changes fro
@ChenyingYang - Thank you. Initially, it was a bit confusing to me but now it makes perfect sense. I am happy to leave it as is. please mark my comment as resolved.

2021-01-05 03:18 UTC, JohanFreelancer9 approved these changes

2021-01-06 03:40 UTC, merged