Adding SQL2014
MicrosoftDocs/OfficeDocs-SharePoint pull request #2560
Opened 2021-01-21 20:15 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2555

@tseward can you kindly review? Thanks

2021-01-22 15:13 UTC, tseward approved these changes

2021-01-25 03:06 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-01-25 05:00 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/install/hardware-and-software-requirements-0.md
> +  - The 64-bit edition of SQL Server 2014 (requires May 2014 Cumulative update for SharePoint Server 2013).
```suggestion
  - The 64-bit edition of SQL Server 2014 (requires May 2014 cumulative update for SharePoint Server 2013).
```

2021-01-25 05:00 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-01-25 14:24 UTC, JohanFreelancer9 approved these changes

2021-01-27 04:32 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-18 04:03 UTC, merged