Update control-access-based-on-network-location.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2590
Opened 2021-02-15 00:01 UTC by SanjoyanM

We have found a issue where users using Office.com was able to bypass this policy. Hence we have added the below line to make customers aware to configure the policy correctly for Office.com.

"For protecting access to SharePoint via Office.com portal we recommend using Azure Active Directory conditional access policy for SharePoint app and configure the trusted IP range there. "

2021-02-17 03:00 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-17 10:00 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/control-access-based-on-network-location.md
> +    > We recommend that when a location-based policy is enabled for SharePoint, the same policy and IP address ranges should be configured for Exchange and Yammer. SharePoint relies on these services
```suggestion
    > We recommend that when a location-based policy is enabled for SharePoint, the same policy and IP address ranges should be configured for Exchange and Yammer. SharePoint relies on these services to enforce that the users of these apps are within the trusted IP range. For protecting access to SharePoint via the Office.com portal we recommend using the Azure Active Directory conditional access policy for "Office 365" and configuring the trusted IP range there. 
```

2021-02-17 10:07 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-19 03:29 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-03 00:28 UTC, merged