Update view-search-usage-reports.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2598
Opened 2021-02-18 23:02 UTC by wbaer

Updated timeline for deprecation.

2021-02-19 03:30 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-19 06:47 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/view-search-usage-reports.md
> +>Beginning in Q4 CY2021, we'll be retiring classic tenant-wide search usage reports in SharePoint Online.  After this change, you will be able to discover site collection search usage data through th
```suggestion
>Starting in the fourth quarter of 2021, we'll be retiring classic tenant-wide search usage reports in SharePoint Online.  After this change, you will be able to discover site collection search usage data through the classic site collection usage reports under the **Site** > **Site Settings** > **Site collection Administration** > **Search Reports** where you can access and download usage data for the last 31 days and past 12 months. For administrators of Microsoft Search you can access the tenant usage analytics reports through the Microsoft 365 admin center under **Settings** > **Search and Intelligence** > **Insights**.
```

2021-02-19 06:48 UTC, JohanFreelancer9 requested changes
Copy review.

2021-02-21 22:20 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-18 04:03 UTC, merged