Update information-architecture-modern-experience.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2600
Opened 2021-02-22 15:39 UTC by SusanHanley

Corrected spelling errors and adjusted the section about global navigation to include the app bar. Also moved sections around for better flow. and deleted sections that added too much detail about hubs given the context of this article.

2021-02-24 16:43 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-02-25 06:21 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/information-architecture-modern-experience.md
> +The goal of global navigation is to support browsing to content, but since there is limited real estate available for global navigation links, global links generally point to major category navigatio
```suggestion
The goal of global navigation is to support browsing to content, but since there is limited real estate available for global navigation links, global links generally point to major category navigation pages, sub-links, or a mega menu experience to provide enough "information scent" to help viewers navigate their way to the content they need. Because the context for global navigation must be broad, it is challenging to make the labels both comprehensive and useful. If you plan to implement global navigation, you will want to test your proposed navigation to make sure that it resonates with users.
```

2021-02-25 06:24 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/information-architecture-modern-experience.md
> +SharePoint [hubs](https://support.microsoft.com/office/what-is-a-sharepoint-hub-site-fe26ae84-14b7-45b6-a6d1-948b3966427f) help organize related sites based on project, department, division, region,
```suggestion
SharePoint [hubs](https://support.microsoft.com/office/what-is-a-sharepoint-hub-site-fe26ae84-14b7-45b6-a6d1-948b3966427f) help organize related sites based on project, department, division, region, or concept. Hubs make it easier to discover related content such as news and other site activities, apply common navigation, branding, site structure across associated sites, and search across all [associated sites](https://support.microsoft.com/office/associate-a-sharepoint-site-with-a-hub-site-ae0009fd-af04-4d3d-917d-88edb43efc05). One of the important planning decisions for hubs is [planning the hub navigation](https://docs.microsoft.com/sharepoint/planning-hub-sites).
```

2021-02-25 06:30 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/information-architecture-modern-experience.md
> +One component to modern SharePoint team sites that makes information architecture easier to implement and maintain are [Microsoft 365 groups](https://docs.microsoft.com/microsoft-365/admin/create-gro
```suggestion
One component to modern SharePoint team sites that makes information architecture easier to implement and maintain is [Microsoft 365 groups](https://docs.microsoft.com/microsoft-365/admin/create-groups/office-365-groups). Microsoft 365 groups provide a membership service that allows for easy hub and site permissions as well as additional functionality for SharePoint team sites and [Microsoft Teams](https://docs.microsoft.com/microsoftteams/office-365-groups). With Microsoft 365 groups, you can give a group of people access to a collection of collaboration resources like Planner, OneNote, SharePoint team sites, and more. Microsoft 365 groups can only be used on SharePoint team sites.
```

2021-02-25 06:35 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/information-architecture-modern-experience.md
>  Since we know that most readers do not read every word on a web page or even scroll to the bottom, you need to pay attention to how you present information on each page. Make sure that you put the mo
```suggestion
Since we know that most readers do not read every word on a web page or even scroll to the bottom, you need to pay attention to how you present information on each page. Make sure that you put the most important information – the information that your readers must have for your communication to be successful – at the top of the page. As the page continues, you can add additional information that is helpful, but not crucial. Think of this as writing with your summary or conclusion up front, instead of at the end. Use sections, headings, and bullets to make your pages easier to read. For more info, see [Add sections and columns on a SharePoint modern page](https://support.microsoft.com/office/fc491eb4-f733-4825-8fe2-e1ed80bd0899).
```

2021-02-25 06:36 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-01 05:11 UTC, scanum commented
@Holland-ODSP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-02 15:54 UTC, Holland-ODSP approved these changes

2021-03-02 15:54 UTC, merged