Note removal of timer job in SharePoint 2019
MicrosoftDocs/OfficeDocs-SharePoint pull request #2646
Opened 2021-03-21 08:54 UTC by TroyStarr

The "Document and List Static Data Fixed Sample job" timer job is removed from SharePoint Server 2019 by the March 2021 Public Update for SharePoint Server 2019 (KB 4493230). Updating the documentation with this information.

2021-03-24 19:13 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-25 06:01 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/technical-reference/default-timer-jobs-in-sharepoint-server-2019.md
> +<a name="Note1"><sup>1</sup></a> This timer job is not needed by SharePoint Server 2019 and is removed by the <a href="https://support.microsoft.com/topic/description-of-the-security-update-for-share
```suggestion
<a name="Note1"><sup>1</sup></a> This timer job is not needed by SharePoint Server 2019 and is removed by the <a href="https://support.microsoft.com/topic/description-of-the-security-update-for-sharepoint-server-2019-march-9-2021-kb4493230-123bf257-222a-41f5-2ad4-96efe8b5df87">security update for SharePoint Server 2019: March 9, 2021 (KB4493230)</a>.
```

2021-03-25 06:01 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-03-25 18:10 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-25 18:11 UTC, scanum commented
@TroyStarr hope you are well. Wondering if the changes that Johan suggested can be made? Thanks

2021-03-25 18:13 UTC, TroyStarr commented
Hi @scanum, yeah, Johan's changes look good to me.  Feel free to proceed with them.  Thanks!

2021-03-26 05:20 UTC, JohanFreelancer9 approved these changes

2021-03-29 04:43 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-25 22:34 UTC, merged