Fix the link for the SharePoint management shell
MicrosoftDocs/OfficeDocs-SharePoint pull request #2649
Opened 2021-03-22 17:47 UTC by derhallim

Management shell link is broken. Related to Issue #2648

2021-03-24 19:14 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-24 22:20 UTC, derhallim commented
Resolved merge conflicts.

2021-03-25 07:21 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sharepoint-app-bar.md
> +1.	Download the latest version of [SharePoint Online Management Shell](https://www.microsoft.com/en-us/download/details.aspx?id=35588).
```suggestion
1.	Download the latest version of [SharePoint Online Management Shell](https://www.microsoft.com/download/details.aspx?id=35588).
```

2021-03-25 07:25 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sharepoint-app-bar.md
> +1.	Download the latest version of [SharePoint Online Management Shell](https://www.microsoft.com/en-us/download/details.aspx?id=35588).
```suggestion
1.	Download the latest version of [SharePoint Online Management Shell](https://www.microsoft.com/download/details.aspx?id=35588).
```

2021-03-25 07:25 UTC, JohanFreelancer9 requested changes
Copy review - please remove the locale from the link.

2021-03-25 18:11 UTC, scanum commented
@Holland-ODSP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-25 18:27 UTC, merged