Updated steps to create classic sites.
MicrosoftDocs/OfficeDocs-SharePoint pull request #2650
Opened 2021-03-22 18:23 UTC by derhallim

M365 Admin Center will route users to the SP admin center. Existing steps are no longer valid. Fix for issue #2632

2021-03-24 19:14 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-25 06:45 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/create-site-collection.md
> +1. Sign in to SharePoint Admin Center (Would be at https://[tenant-name]-admin.sharepoint.com) as a SharePoint admin.
```suggestion
1. Sign in to the SharePoint admin center (at https://[tenant-name]-admin.sharepoint.com) as a SharePoint admin. 
```

2021-03-25 06:45 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/create-site-collection.md
> +2. In the left pane, select **Sites** \> **Active Sites**.
```suggestion
2. In the left pane, select **Sites** > **Active Sites**. 
```

2021-03-25 06:46 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/create-site-collection.md
> +4. At the bottom of the panel, click **"Other options"**:
```suggestion
4. At the bottom of the panel, select**Other options**:
```

2021-03-25 06:47 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/create-site-collection.md
> +5. From the template drop-down, select "More templates"
```suggestion
5. From the template drop-down, select **More templates**. 
```

2021-03-25 06:50 UTC, JohanFreelancer9 requested changes
Copy review.

2021-03-25 18:12 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-03-25 22:11 UTC, merged