Update sharepoint-server-2016-zero-downtime-patching-steps.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2656
Opened 2021-03-25 12:37 UTC by HolgerLutz

Since March 2017 update, we always copy the Side-by-side files, even if the WebService.EnableSideBySide has still its default value set to $false.
So you still have to run the PS script below to enable the side-by-side functionality at all, before you set the WebService.SideBySideToken as outlined at Phase 2 - 4. further down in the documentation:
`$webapp = Get-SPWebApplication <webappURL>`  
`$webapp.WebService.EnableSideBySide = $true`  
`$webapp.WebService.update()`

2021-03-29 04:42 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-03-29 08:51 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md
> +> To enable the side-by-side functionality, execute the following PowerShell script once by using the URL for one of the content web-applications:
```suggestion
> To enable the side-by-side functionality, execute the following PowerShell script once by using the URL for one of the content web applications:
```

2021-03-29 09:01 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/upgrade-and-update/sharepoint-server-2016-zero-downtime-patching-steps.md
> +> As of [KB3178672](https://support.microsoft.com/help/3178672) (March 2017 update) for SharePoint Server 2016 and above, PSCONFIG will automatically copy all .js, .css and .htm files within the `16-
```suggestion
> As of [KB3178672](https://support.microsoft.com/help/3178672) (March 2017 update) for SharePoint Server 2016 and above, PSCONFIG will automatically copy all .js, .css, and .htm files within the `16-HIVE\TEMPLATE\LAYOUTS` folder to the `16-HIVE\TEMPLATE\LAYOUTS\<NEW BUILD NUMBER>` folder, required to be able to switch to the new user interface files and complete the side-by-side process as outlined later in this topic in **Phase 2 - PSCONFIG upgrade (4)**.
```

2021-03-29 09:04 UTC, JohanFreelancer9 requested changes
Copy review - @HolgerLutz please commit my suggested changes if you agree.

2021-04-07 00:56 UTC, scanum commented
@HolgerLutz please commit my suggested changes if you agree.

2021-05-18 15:14 UTC, MikePlumleyMSFT commented
@TroyStarr can you review?

2021-05-19 07:15 UTC, JohanFreelancer9 approved these changes

2021-06-25 22:37 UTC, merged