Updating KFMBlockOptIn policy
MicrosoftDocs/OfficeDocs-SharePoint pull request #2678
Opened 2021-04-01 20:42 UTC by cartergreen

KFMBlockOptIn Policy has been updated with a new reg key to redirect known folders back to user's device.

2021-04-01 20:43 UTC, cartergreen commented
@adeejoseph FYI

2021-04-05 05:12 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-05 08:21 UTC, JohanFreelancer9 commented on OneDrive/use-group-policy.md
> +If you enable this setting, users aren't prompted with a window to protect their important folders, and the *Manage backup* command is disabled. If the user has already moved their known folders, the
```suggestion
If you enable this setting, users aren't prompted with a window to protect their important folders, and the *Manage backup* command is disabled. If the user has already moved their known folders, the files in those folders will remain in OneDrive. To redirect the known folders back to the user's device, please select "No." This setting does not take effect if you've enabled "Prompt users to move Windows known folders to OneDrive" or "Silently move Windows known folders to OneDrive."
```

2021-04-05 08:22 UTC, JohanFreelancer9 commented on OneDrive/use-group-policy.md
> +To redirect the known folders back to user's device and enable this policy set the following registry key value to 2:
```suggestion
To redirect the known folders back to the user's device and enable this policy, set the following registry key value to 2:
```

2021-04-05 08:23 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-06 02:08 UTC, scanum commented
@adeejoseph PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-06 05:24 UTC, JohanFreelancer9 approved these changes

2021-04-12 18:35 UTC, merged