Added missing step
MicrosoftDocs/OfficeDocs-SharePoint pull request #2692
Opened 2021-04-09 10:18 UTC by derhallim

Select settings is required before select sync.

2021-04-09 10:18 UTC, derhallim commented
Related to #2673

2021-04-12 15:22 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-13 06:17 UTC, JohanFreelancer9 commented on OneDrive/block-file-types.md
> +2. Select **Settings** in the left menu then select **Sync**.
```suggestion
2. Select **Settings** in the left menu, then select **Sync**.
```

2021-04-13 06:18 UTC, JohanFreelancer9 requested changes
Copy review.

2021-04-14 05:16 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-04-14 09:20 UTC, JohanFreelancer9 commented
@derhallim - please commit my minor suggested change. Thanks.

2021-04-22 23:24 UTC, kaarins commented
Step 1 is "Go to the Settings page of the new SharePoint admin center" and it links directly to the Settings page.

2021-04-22 23:24 UTC, closed without merging