Update sharepoint-app-bar.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2705
Opened 2021-04-27 18:49 UTC by petey121175

I thought this was documented already as I remember seeing this somewhere. Currently, the App Bar is not available to external users of an organization. We have a couple reports of this and I was able to repro as well. Will send note to Holland too.

2021-04-29 05:13 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-04-29 09:12 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sharepoint-app-bar.md
> +> - The SharePoint app bar is not available to guest users outside of your organization.
```suggestion
> -	The SharePoint app bar is not available to guest users outside of your organization.
```

2021-04-29 09:13 UTC, JohanFreelancer9 requested changes
Copy review - minor formatting suggestion.

2021-05-03 04:17 UTC, scanum approved these changes

2021-05-03 04:18 UTC, scanum commented
@Holland-ODSP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-03 16:46 UTC, Holland-ODSP approved these changes

2021-05-03 16:46 UTC, merged

2021-05-03 16:46 UTC, Holland-ODSP commented
Approved