Add EnableODIgnore setting to docs
MicrosoftDocs/OfficeDocs-SharePoint pull request #2709
Opened 2021-04-29 07:51 UTC by gacarini

This is the new "exclude files from sync" setting (aka ODIgnore).

2021-04-29 07:52 UTC, gacarini commented
@adeejoseph @cartergreen fyi on this PR for ODIgnore on macOS

2021-05-03 04:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-03 05:57 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +This setting lets you enter keywords to prevent the OneDrive sync app from uploading certain files to OneDrive or SharePoint. You can enter complete names, such as "setup.exe" or use the asterisk (*)
```suggestion
This setting lets you enter keywords to prevent the OneDrive sync app from uploading certain files to OneDrive or SharePoint. You can enter complete names, such as "setup.exe" or use the asterisk (*) as a wildcard character to represent a series of characters, such as *.pst. Keywords aren't case-sensitive.
```

2021-05-03 06:04 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +Set this setting's value to an integer between 50 KB/sec and the maximum rate is 100,000 KB/sec that determines the download throughput in KB/sec that the sync app can use.
```suggestion
Set this setting's value to an integer between 50 KB/sec and the maximum rate of 100,000 KB/sec that determines the download throughput in KB/sec that the sync app can use.
```

2021-05-03 06:07 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-05-03 06:58 UTC, JohanFreelancer9 approved these changes

2021-05-05 04:37 UTC, scanum commented
@adeejoseph PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-08 20:19 UTC, merged