Add new note about GA integration abilities
MicrosoftDocs/OfficeDocs-SharePoint pull request #2710
Opened 2021-04-29 14:33 UTC by salarson

2021-05-03 04:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-03 05:41 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md
> + > When the integration flag is enabled, external users will be invited via the Azure B2B platform when sharing from SPO. If Azure B2B One Time Passcode option is enabled, recipients that do not have
```suggestion
 > When the integration flag is enabled, external users will be invited via the Azure B2B platform when sharing from SharePoint. If the Azure B2B One Time Passcode option is enabled, recipients that do not have password-backed accounts will get a sign-in experience through Azure AD that uses One Time Passcodes. Otherwise, external users will authenticate via their own Azure AD account or via an MSA account.
```

2021-05-03 05:50 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sharepoint-azureb2b-integration.md
> +When the integration flag is not enabled, external users will continue to use their existing accounts previously invited to the tenant. Any sharing to new external users may result in either AAD back
```suggestion
When the integration flag is not enabled, external users will continue to use their existing accounts created when previously invited to the tenant. Any sharing to new external users may result in either Azure AD-backed accounts or SharePoint-only email auth guests that use a SharePoint One Time Passcode experience to sign in.
```

2021-05-03 05:51 UTC, JohanFreelancer9 requested changes
Copy review - suggestions.

2021-05-03 13:55 UTC, JohanFreelancer9 commented
@salarson - thank you for committing my suggestions but I notice you have also closed the PR. Was that intentional?

2021-05-03 13:56 UTC, salarson commented
Complete accident! Sorry about that!

From: JohanFreelancer9 ***@***.***>
Sent: Monday, May 3, 2021 8:56 AM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Sam Larson ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Add new note about GA integration abilities (#2710)


@salarson<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsalarson&data=04%7C01%7Csalarson%40microsoft.com%7C105f52d69b4044d7d18a08d90e3b33f4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637556469703497600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=18e0Y9atJMCJSp6%2F7kh4%2ByC%2FhsVSD4feW2EtAVZP7Mc%3D&reserved=0> - thank you for committing my suggestions but I notice you have also closed the PR. Was that intentional?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fpull%2F2710%23issuecomment-831275831&data=04%7C01%7Csalarson%40microsoft.com%7C105f52d69b4044d7d18a08d90e3b33f4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637556469703502578%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BWxliXqk%2FpP0NnF%2FHNQD5XJAqBALc1Eyky3ta8sTVxc%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFBR4UPOR2VMZYL2MWT5J5TTL2TPRANCNFSM432A4LDA&data=04%7C01%7Csalarson%40microsoft.com%7C105f52d69b4044d7d18a08d90e3b33f4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637556469703507556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=di09JQTCT5rr4t2de4Dfy5LwBI6Y%2BTcUDUoOtlpbMTo%3D&reserved=0>.

2021-05-03 13:59 UTC, JohanFreelancer9 commented
No problem. Please reopen and I will approve the copy.

2021-05-03 14:04 UTC, JohanFreelancer9 approved these changes

2021-05-04 16:43 UTC, MikePlumleyMSFT commented
@salarson I made some terminology tweaks. Is this set to be merged? I know there was some discussion in mail about what to include in the note...

2021-05-06 14:58 UTC, merged