Update manage-security-groups.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2711
Opened 2021-04-30 18:34 UTC by StephenRiceMSFT

Updating to improve clarity around what types of groups are approved.

2021-05-03 04:18 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-03 05:20 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-security-groups.md
> +4. In the **Add a security group** box, enter a name for a security group (Note that Microsoft 365 Groups are not supported). The security group box appears.
```suggestion
4. In the **Add a security group** box, enter a name for a security group. The security group box appears.

> [!NOTE]
> Microsoft 365 Groups are not supported.
```

2021-05-03 05:21 UTC, JohanFreelancer9 requested changes
Copy review - suggestion.

2021-05-03 05:22 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-security-groups.md
> +4. In the **Add a security group** box, enter a name for a security group (Note that Microsoft 365 Groups are not supported). The security group box appears.
```suggestion
4. In the **Add a security group** box, enter a name for a security group (note that Microsoft 365 Groups are not supported). The security group box appears.
```

2021-05-05 04:37 UTC, scanum approved these changes

2021-05-12 03:55 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-12 08:17 UTC, JohanFreelancer9 requested changes
@StephenRiceMSFT, please commit this minor suggested change. Many thanks.

2021-05-12 13:04 UTC, merged