Clarifying about geo
MicrosoftDocs/OfficeDocs-SharePoint pull request #2718
Opened 2021-05-06 11:56 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2694

2021-05-12 03:54 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-12 09:06 UTC, JohanFreelancer9 commented on OneDrive/allow-syncing-only-on-specific-domains.md
> +> In a Multi-Geo environment, this setting can be configured separately for each geo location and applies to users with that perferred data location.
```suggestion
> In a multi-geo environment, this setting can be configured separately for each geo location and applies to users with that preferred data location.
```

2021-05-12 09:11 UTC, JohanFreelancer9 requested changes
Copy review - suggestion.

2021-05-12 16:33 UTC, JohanFreelancer9 approved these changes

2021-05-17 18:01 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-05-18 15:34 UTC, merged