Added PnP.PowerShell Set-PnPSite cmdlet
MicrosoftDocs/OfficeDocs-SharePoint pull request #2745
Opened 2021-05-21 13:55 UTC by Markus-Hanisch

Added PnP.PowerShell Set-PnPSite cmdlet to allow custom scripts on a specific SharePoint site:
```powershell
Set-PnPSite <SiteURL> -NoScriptSite $false
```
Further info: [Set-PnPSite](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps)

2021-05-24 05:16 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-24 06:52 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/allow-or-prevent-custom-script.md
> +    or by means of PnP.PowerShell cmdlet [Set-PnPSite](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps)
```suggestion
    or by means of the PnP.PowerShell cmdlet [Set-PnPSite](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnpsite?view=sharepoint-ps)
```

2021-05-24 06:54 UTC, JohanFreelancer9 requested changes
Copy review. @Markus-Hanisch, please commit my suggested change.

2021-05-24 07:42 UTC, Markus-Hanisch commented
@JohanFreelancer9 done

2021-05-24 08:48 UTC, JohanFreelancer9 approved these changes

2021-05-25 17:41 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-08 18:33 UTC, merged