Update how-to-create-and-edit-permission-levels.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2755
Opened 2021-05-28 14:39 UTC by jwaite007

Reach out to JWaite at Microsoft for more info if needed.

2021-05-28 21:08 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-05-29 08:14 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/how-to-create-and-edit-permission-levels.md
> +> It is possible to create permission levels which do not grant the minimum required permissions. The modern user experience uses client side rendering which requires that all users have the "Use Rem
```suggestion
> It is possible to create permission levels that do not grant the minimum required permissions. The user experience uses client-side rendering which requires that all users have the **Use Remote Interfaces** permission. Removing Use **Remote Permissions** from a permissions level will result in **Access Denied** errors that either prevent features on a page from loading or prevent the entire page from loading, resulting in an **Access Denied** error for the user. 
```

2021-05-29 08:17 UTC, JohanFreelancer9 requested changes
Copy review - @jwaite007, please commit my recommended changes if you agree. For information, the term "modern" is now discouraged in Microsoft docs as it is jargon that means very little (except for "modern authentication", which is an officially blessed term). Many thanks.

2021-05-31 13:42 UTC, jwaite007 commented
> Copy review - @jwaite007, please commit my recommended changes if you agree. For information, the term "modern" is now discouraged in Microsoft docs as it is jargon that means very little (except for "modern authentication", which is an officially blessed term). Many thanks.

How do we differentiate that this issue only happens with our new user experience pages which use client side rendering without using the word modern? This isn't an issue with the classic pages and customers that have removed Use Remote Interfaces are now having problems as we push out new features which rely on client side rendering.

2021-05-31 16:53 UTC, JohanFreelancer9 approved these changes
@jwaite007 - Thank you for clarifying. I take your point and have deleted my suggested changes.

2021-05-31 21:19 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-01 13:30 UTC, merged