Clarified the requirement that locations need to be explicitly allowed in at least one DLP policy for sharing to work
MicrosoftDocs/OfficeDocs-SharePoint pull request #2783
Opened 2021-06-14 20:16 UTC by Esaggese

…e DLP policy for sharing to work.

The requirement to create a DLP policy with all locations and all users was opaque and many customers were asking for clarification. I added an explanation about the source of this requirement, and detailed that the option to create a DLP policy with all sites and all users is only required if you don't want to require that locations are explicitly authorized in a DLP policy for them to be shareable.

2021-06-16 01:28 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-16 05:56 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sensitive-by-default.md
> +Instead of turning off external sharing entirely, you can address this issue by using a PowerShell cmdlet to block external access to new content unless it's explicitly authorized in a DLP rule and i
```suggestion
Instead of turning off external sharing entirely, you can address this issue by using a PowerShell cmdlet to block external access to new content unless it's explicitly authorized in a DLP rule and it has been verified that there's no sensitive content that goes against the policy rules. The setting enabled by this cmdlet prevents external users from accessing newly added files until at least one Office DLP policy scans the content and determines that the document doesn't contain any sensitive information that's against the rules defined in the policy. If the file has been indexed and scanned and it has no sensitive content that's against the rules in the DLP policy, then guests can access the file. If the policy identifies sensitive content in the document, or if there's no DLP rule explicitly authorizing access to the file, then guests will not be able to access the file, and they will receive the following access denied error message: "This file is being scanned right now. Please try again in a few minutes. If you still don't have access, contact the file owner."
```

2021-06-16 05:57 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sensitive-by-default.md
> +Instead of turning off external sharing entirely, you can address this issue by using a PowerShell cmdlet to block external access to new content unless it's explicitly authorized in a DLP rule and i
Please correct the typo in the second instance of "document" (not "docment").

2021-06-16 06:01 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sensitive-by-default.md
> +1. Since once this setting is enabled any content not explicitly checked in a DLP policy will be blocked from being externally accessed, you must ensure any content that needs to be shared externally
```suggestion
1. Since once this setting is enabled any content not explicitly checked in a DLP policy will be blocked from being externally accessed, you must ensure any content that needs to be shared externally is covered by at least one DLP policy. If you prefer to require explicit authorization in a DLP policy for a site to be shareable, no further action is needed after this setting is enabled. If not all locations with content that needs to be shared externally are already covered by an existing DLP policy, you must add them to at least one policy. The easiest way to do this is to create a DLP policy that includes all locations that have any “content contains” condition selected, and that specifies no actions, no alerts, no notifications, and no reports. Also, make sure the rule doesn’t use the option to stop processing additional DLP rules. [Learn how to create and turn on a DLP policy](/microsoft-365/compliance/create-test-tune-dlp-policy)
```

2021-06-16 06:02 UTC, JohanFreelancer9 requested changes
Copy review - @Esaggese, kindly commit my suggested changes. Many thanks.

2021-06-17 04:04 UTC, JohanFreelancer9 requested changes
@Esaggese - I have edited my suggestion in line with your comment. Could you please commit? Many thanks.

2021-06-28 17:42 UTC, merged