Update sensitive-by-default.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2784
Opened 2021-06-14 20:21 UTC by Esaggese

The requirement to create a DLP policy with all locations and all users was opaque and many customers were asking for clarification. I added an explanation about the source of this requirement, and detailed that the option to create a DLP policy with all sites and all users is only required if you don't want to require that locations are explicitly authorized in a DLP policy for them to be shareable.

2021-06-14 20:21 UTC, Esaggese commented
Just fixed some typos in my previous edit.

2021-06-16 01:29 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-16 05:43 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sensitive-by-default.md
> +1. Since once this setting is enabled any content not explicitly checked in a DLP policy will be blocked from being externally accessed, you must ensure any content that needs to be shared externally
```suggestion
1. Since once this setting is enabled any content not explicitly checked in a DLP policy will be blocked from being externally accessed, you must ensure any content that needs to be shared externally is covered by at least one DLP policy. If you prefer to require explicit authorization in a DLP policy for a site to be shareable, no further action is needed after this setting is enabled. If not all locations with content that needs to be shared externally are already covered by an existing DLP policy, you must add them to at least one policy. The easiest way to do this is to create a DLP policy that includes all locations that have any “content contains” condition selected, and that specifies no actions, no alerts, no notifications, and no reports. Also, make sure the rule doesn’t use the option to stop processing additional DLP rules. [Learn how to create and turn on a DLP policy](/microsoft-365/compliance/create-test-tune-dlp-policy)
```

2021-06-16 05:48 UTC, JohanFreelancer9 requested changes
Copy review - @Esaggese, please commit my minor suggested changes. Many thanks.

2021-06-16 22:29 UTC, Esaggese commented on SharePoint/SharePointOnline/sensitive-by-default.md
> +1. Since once this setting is enabled any content not explicitly checked in a DLP policy will be blocked from being externally accessed, you must ensure any content that needs to be shared externally
@JohanFreelancer9 I don't think the has -> have change is correct, since has refers to the DLP policy, not to the locations. So I think we could make it clearer by reordering it as: 
The easiest way to do this is to create a DLP policy that has a “content contains” condition selected, and that specifies no actions, no alerts, no notifications, and no reports, and that includes all locations in its scope.

Do you agree with the proposed wording?

2021-06-17 04:07 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sensitive-by-default.md
> +1. Since once this setting is enabled any content not explicitly checked in a DLP policy will be blocked from being externally accessed, you must ensure any content that needs to be shared externally
Agree. I have edited my suggestion accordingly. Could you please commit? Many thanks.

2021-06-17 04:08 UTC, JohanFreelancer9 requested changes
Copy review.

2021-06-17 09:42 UTC, JohanFreelancer9 approved these changes

2021-06-28 17:44 UTC, closed without merging