Updating the Tier preferences with modern format
MicrosoftDocs/OfficeDocs-SharePoint pull request #2791
Opened 2021-06-16 06:23 UTC by cartergreen

2021-06-17 04:04 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-17 07:51 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +This setting lets you specify the ring for users in your organization. The OneDrive sync app updates to the public through three rings- first to Insiders, then Production, and finally Deferred.  When
```suggestion
This setting lets you specify the ring for users in your organization. The OneDrive sync app updates to the public through three rings; first to Insiders, then to Production, and finally to Deferred.  When you enable this setting and select a ring, users aren't able to change it.  
```

2021-06-17 07:52 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +Insiders - This update ring users receive builds that let them preview new features coming to OneDrive.
```suggestion
**Insiders**: The Insiders ring users receive builds that let them preview new features coming to OneDrive.
```

2021-06-17 07:55 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +Enterprise (now called "Deferred") - This update ring users get new features, bug fixes, and performance improvements last. This ring lets you deploy updates from an internal network location, and co
```suggestion
**Enterprise** (now called "Deferred"): The Deferred ring users get new features, bug fixes, and performance improvements last. This ring lets you deploy updates from an internal network location, and control the timing of the deployment (within a 60-day window).
```

2021-06-17 07:56 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +> We recommend selecting several people in your IT department as early adopters to join the Insiders ring and receive features early. We recommend leaving everyone else in the organization in the def
```suggestion
> We recommend selecting several people in your IT department as early adopters to join the Insiders ring and receive features early. We also recommend leaving everyone else in the organization in the default Production ring to ensure they receive bug fixes and new features in a timely fashion. [See all our recommendations for configuring the sync app](ideal-state-configuration.md).
```

2021-06-17 07:57 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +For more info on the builds currently available in each ring, see the [release notes](https://support.office.com/article/845dcf18-f921-435e-bf28-4e24b95e5fc0?). For more info about the update rings a
```suggestion
For more information on the builds currently available in each ring, see the [release notes](https://support.office.com/article/845dcf18-f921-435e-bf28-4e24b95e5fc0?). For more information about the update rings and how the sync app checks for updates, see the [OneDrive sync app update process](sync-client-update-process.md).
```

2021-06-17 08:03 UTC, JohanFreelancer9 requested changes
Copy review - @cartergreen, please commit my suggested changes if you agree with them. Many thanks.

2021-06-18 20:48 UTC, cartergreen commented
I have made all the changes that @JohanFreelancer9 suggested.  Thanks again for the great work.

2021-06-18 21:50 UTC, scanum commented
@adeejoseph PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-06-19 03:45 UTC, JohanFreelancer9 approved these changes

2021-08-05 01:33 UTC, scanum commented
@adeejoseph PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-13 19:04 UTC, adeejoseph approved these changes

2021-08-13 19:04 UTC, merged