Update tenant-rename.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2809
Opened 2021-06-21 20:34 UTC by WayneEwington

Clarified that this feature is only available for customers that have been accepted into the Private Preview.
Called out that third-party applications including backup solutions should be confirmed to support tenant renames.

2021-06-22 15:23 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-06-23 07:06 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/tenant-rename.md
> +> This feature is available isn't available for organizations that have set up Multi-geo.
```suggestion
> This feature is not available for organizations that have set up a multi-geo.
```

2021-06-23 07:11 UTC, JohanFreelancer9 requested changes
Copy review - @WayneEwington, kindly commit mu suggested changes if you agree with them. Many thanks.

2021-06-23 07:15 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/tenant-rename.md
> +> This feature is available isn't available for organizations that have set up Multi-geo.
```suggestion
> - This feature is not available for organizations that have set up a multi-geo.
```

2021-06-24 04:46 UTC, JohanFreelancer9 approved these changes

2021-06-24 19:50 UTC, merged