updating to reflect new feature
MicrosoftDocs/OfficeDocs-SharePoint pull request #2841
Opened 2021-07-08 13:26 UTC by get-itips

Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2838

@kaarins What do you think? :)

2021-07-09 16:27 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-10 04:30 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md
> +It's now possible to change the SharePoint domain name, see [Rename your SharePoint domain](tenant-rename.md) for more information.
```suggestion
It's now possible to change the SharePoint domain name; see [Rename your SharePoint domain](tenant-rename.md) for more information.
```

2021-07-10 04:31 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-07-12 13:58 UTC, JohanFreelancer9 approved these changes

2021-07-12 18:01 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-03 22:51 UTC, get-itips commented
@scanum @kaarins can we merge this? Thank you!

2021-08-10 21:36 UTC, kaarins commented
We're not ready to add this to the main article just yet. :)

2021-08-10 21:36 UTC, closed without merging