Update how-to-format-your-csv-file-for-data-content-migration.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2849
Opened 2021-07-13 11:51 UTC by modery

Some smaller fixes and some clarifications on what needs to go into the CSV file

2021-07-13 20:34 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-14 05:42 UTC, JohanFreelancer9 commented on migration/how-to-format-your-csv-file-for-data-content-migration.md
> +|RegisterAsHubSite|Indicate if you want the destination site be be a hub site. Enter **YES** or **NO**. If you say **YES**, do not put a value in the *AssociateWithHubURL* column.Nested hub sites are
```suggestion
|RegisterAsHubSite|Indicate if you want the destination site be be a hub site. Enter **YES** or **NO**. If you say **YES**, do not put a value in the *AssociateWithHubURL* column.Nested hub sites are not supported.|
```
```suggestion
|RegisterAsHubSite|Indicate if you want the destination site to be a hub site. Enter **YES** or **NO**. If you say **YES**, do not put a value in the *AssociateWithHubURL* column. Nested hub sites are not supported.|
```

2021-07-14 05:44 UTC, JohanFreelancer9 commented on migration/how-to-format-your-csv-file-for-data-content-migration.md
> +|RegisterAsHubSite|Indicate if you want the destination site be be a hub site. Enter **YES** or **NO**. If you say **YES**, do not put a value in the *AssociateWithHubURL* column.Nested hub sites are
```suggestion
|RegisterAsHubSite|Indicate if you want the destination site to be a hub site. Enter **YES** or **NO**. If you say **YES**, do not put a value in the *AssociateWithHubURL* column. Nested hub sites are not supported.|
```

2021-07-14 05:47 UTC, JohanFreelancer9 requested changes
Copy review. @modery, kindly commit the suggested changes. Many thanks.

2021-07-14 06:52 UTC, modery commented
Suggestions committed, all ok for me

2021-07-14 07:21 UTC, JohanFreelancer9 approved these changes

2021-07-15 00:34 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-07-16 14:58 UTC, merged