Adding error code and description
MicrosoftDocs/OfficeDocs-SharePoint pull request #2855
Opened 2021-07-15 21:57 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2852

2021-07-19 17:12 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-20 03:42 UTC, JohanFreelancer9 commented on migration/troubleshooting-common-spmt-issues.md
> +|0x0111000A|Scan File Failure: File size exceeds limit. See [Release Notes: SharePoint Migration Tool (SPMT)](new-and-improved-features-in-the-sharepoint-migration-tool.md) for current limits|
```suggestion
|0x0111000A|Scan File Failure: File size exceeds limit. See [Release Notes: SharePoint Migration Tool (SPMT)](new-and-improved-features-in-the-sharepoint-migration-tool.md) for current limits.|
```

2021-07-20 03:43 UTC, JohanFreelancer9 requested changes
Copy review - minor edit.

2021-07-20 19:31 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-07-21 05:41 UTC, JohanFreelancer9 approved these changes

2021-07-27 20:03 UTC, merged