Fixed typos on the page for "if" and "sand"
MicrosoftDocs/OfficeDocs-SharePoint pull request #2872
Opened 2021-07-21 01:37 UTC by vijayysisodia

Updated this page and fixed typos from
a) "To take advantage if this solution" to "To take advantage of this solution"
b) "easy to access sand share content" to "easy to access and share content"

2021-07-24 00:36 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-24 05:12 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/home-site-plan.md
> +| ![image of a globe and monitor](media/icon-launch-viva.png)   | **Integrate the home site into Microsoft Teams using Viva Connections** | Expand the reach of the home site and help meet users where
```suggestion
| ![image of a globe and monitor](media/icon-launch-viva.png)   | **Integrate the home site into Microsoft Teams using Viva Connections** | Expand the reach of the home site and help meet users where they're already working by making it easy to access and share content all in one place. After you have a home site and the global navigation enabled and customized in the SharePoint app bar, you’ve met the requirements to [integrate the home site into Microsoft Teams](/SharePoint/viva-connections) using Viva Connections. Learn more about the [Viva Connections end-user experience](https://support.microsoft.com/office/your-intranet-is-now-in-microsoft-teams-8b4e7f76-f305-49a9-b6d2-09378476f95b).|
```

2021-07-24 05:13 UTC, JohanFreelancer9 requested changes
Copy review - @vijayysisodia, kindly commit the minor additional suggested change. Many thanks.

2021-07-24 05:39 UTC, JohanFreelancer9 approved these changes

2021-07-27 16:47 UTC, scanum commented
@Holland-ODSP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-07-27 18:03 UTC, Holland-ODSP approved these changes

2021-08-05 01:35 UTC, scanum commented
Hi @Holland-ODSP - Could you kindly merge this PR? Thanks

2021-08-05 16:17 UTC, Holland-ODSP commented
Hey Manuela,

I'd be happy to merge but I don't see that as an option in Github. This is what I see:

***@***.***

From: Manuela Scanu ***@***.***>
Sent: Wednesday, August 4, 2021 6:35 PM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Holland Kaviani (SHE/HER) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Fixed typos on the page for "if" and "sand" (#2872)


Hi @Holland-ODSP<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHolland-ODSP&data=04%7C01%7Cholland.kaviani%40microsoft.com%7Cd376c9a74c864ab2c67508d957b14ace%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637637241268521712%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C5sjxyCpBaer95t8BaVGawzQxO%2Ftl2cwy%2FjVayuk6T8%3D&reserved=0> - Could you kindly merge this PR? Thanks

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fpull%2F2872%23issuecomment-893094937&data=04%7C01%7Cholland.kaviani%40microsoft.com%7Cd376c9a74c864ab2c67508d957b14ace%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637637241268531661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iVSfLL2NYUb8mFtzROdz155XVvfHHk4ihlEIRBYXHIo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANKN37QYWWD5QKB6PF2X5T3T3HTFVANCNFSM5AW63YNQ&data=04%7C01%7Cholland.kaviani%40microsoft.com%7Cd376c9a74c864ab2c67508d957b14ace%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637637241268531661%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jM27O%2BEWKuegz1SLpxyLuxBG4LcbdtXMtSOmwSsrj44%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cholland.kaviani%40microsoft.com%7Cd376c9a74c864ab2c67508d957b14ace%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637637241268541621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8Lc4kU2YWAhGV%2BR1NX3FHXN5I6eTUNFW%2B63sjF6478g%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cholland.kaviani%40microsoft.com%7Cd376c9a74c864ab2c67508d957b14ace%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637637241268541621%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BRv0IY%2Fb%2BEpm10Dsn52fNzJAbRDNN4M49Bm6ZapUUwE%3D&reserved=0>.

2021-08-05 17:37 UTC, merged