Update tenant-rename.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2885
Opened 2021-07-28 23:24 UTC by WayneEwington

Removed Power Apps limitations which has now been addressed and addressing key feedback items from Private Preview customers:
* Removed warning about having a hyphen in the MOERA Domain as the UX blocks this.
* Clarified and provided additional information and warning about using the provided "special" hyperlink to add an additional MOERA Domain and the type of domain required.
* Provided additional instructions on how to remove previous versions of TAPS.

2021-07-30 03:15 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-07-30 08:23 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/tenant-rename.md
> +    > Use the hyperlink [https://aka.ms/SPORenameAddDomain](https://aka.ms/SPORenameAddDomain) provided above. Failiure to use this hyperlink will prevent you from successfully adding a custom domain
```suggestion
    > You must use the hyperlink [https://aka.ms/SPORenameAddDomain](https://aka.ms/SPORenameAddDomain). Failure to use this hyperlink will prevent you from successfully adding a custom domain.
```

2021-07-30 08:28 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/tenant-rename.md
> +    > When adding the domain this needs to be a “onmicrosoft.com” domain. For example, if you want to rename your tenant to fabrikam.sharepoint.com, the domain that you enter should be fabrikam.onmic
```suggestion
    > When adding the domain, it needs to be an “onmicrosoft.com” domain. For example, if you want to rename your tenant to fabrikam.sharepoint.com, the domain that you enter should be fabrikam.onmicrosoft.com. The “onmicrosoft.com” domain does not need to be purchased to be added and does not require any public DNS registration.
```

2021-07-30 08:30 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/tenant-rename.md
> +    > If after adding the domain you are prompted to create a new TXT record with your domain name registrar, then the domain has NOT been added correctly and you will NOT be able to perform a rename
```suggestion
    > If, after adding the domain, you are prompted to create a new TXT record with your domain name registrar, then the domain has NOT been added correctly and you will NOT be able to perform a rename. If you are prompted, you will need to delete the invalid domain and return to the previous Step 2.
```

2021-07-30 08:31 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/tenant-rename.md
> +    > The domain name must have the status of "Verified". If the status is NOT "Verified" then you will NOT be able to perform a rename.
```suggestion
    > The domain name must have the status of "Verified". If the status is NOT "Verified", you will NOT be able to perform a rename. 
```

2021-07-30 08:33 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/tenant-rename.md
> +    > If the PowerShell command Start-SPOTenantRename is not found or nothing is returned, then ensure that you have installed the latest SharePoint Online Management Shell. If required, before insta
```suggestion
    > If the PowerShell command Start-SPOTenantRename is not found or nothing is returned, ensure that you have installed the latest SharePoint Online Management Shell. If required, before installing the latest version, you might need to uninstall all previous versions by running `Uninstall-Module Microsoft.Online.SharePoint.PowerShell -Force -AllVersions`.
```

2021-07-30 08:40 UTC, JohanFreelancer9 requested changes
Copy review - @WayneEwington, kindly commit the suggested edits if you agree with them. Many thanks.

2021-08-02 15:52 UTC, WayneEwington commented
@JohanFreelancer9 changes have been committed

2021-08-03 05:22 UTC, JohanFreelancer9 approved these changes

2021-08-03 16:57 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-04 03:00 UTC, merged