Update 5TB section
MicrosoftDocs/OfficeDocs-SharePoint pull request #2891
Opened 2021-08-02 15:47 UTC by salarson

2021-08-03 16:56 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-04 06:16 UTC, JohanFreelancer9 commented on OneDrive/change-user-storage.md
> +Admins can check for OneDrive eligibility beyond 5TB via [Check OneDrive site eligibility for increased storage](https://docs.microsoft.com/en-us/sharepoint/troubleshoot/storage/check-storage-increas
```suggestion
Admins can check for OneDrive eligibility beyond 5 TB via [Check OneDrive site eligibility for increased storage](/sharepoint/troubleshoot/storage/check-storage-increase-eligibility). 
```

2021-08-04 06:17 UTC, JohanFreelancer9 requested changes
Copy review - @salarson, kindly commit the suggested changes. Many thanks.

2021-08-04 18:08 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-08-10 21:38 UTC, merged