Update deeplink for service request 100tb
MicrosoftDocs/OfficeDocs-SharePoint pull request #2924
Opened 2021-08-30 16:10 UTC by salarson

2021-08-30 19:41 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-08-31 06:35 UTC, JohanFreelancer9 commented on migration/sharepoint-online-and-onedrive-migration-speed.md
> +1. As an administrator , click the following link which will populate a help query in the admin center.
```suggestion
1. As an administrator, select the following link which will populate a help query in the admin center. 
```

2021-08-31 06:36 UTC, JohanFreelancer9 commented on migration/sharepoint-online-and-onedrive-migration-speed.md
> +[SharePoint Migration over 100TB](https://admin.microsoft.com/AdminPortal/?searchSolutions=SharePoint%20Migration%20over%20100TB)
```suggestion
[SharePoint Migration over 100 TB](https://admin.microsoft.com/AdminPortal/?searchSolutions=SharePoint%20Migration%20over%20100TB)
```

2021-08-31 06:37 UTC, JohanFreelancer9 commented on migration/sharepoint-online-and-onedrive-migration-speed.md
> +3. Under **Description**, enter "SharePoint Migration over 100TB".
```suggestion
3. Under **Description**, enter "SharePoint Migration over 100 TB". 
```

2021-08-31 06:42 UTC, JohanFreelancer9 requested changes
Copy review - @salarson, kindly commit the minor suggested change. Many thanks.

2021-08-31 15:18 UTC, JohanFreelancer9 approved these changes

2021-09-01 18:48 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-09-08 18:36 UTC, merged