Fixed formatting for the list of OneDrives
MicrosoftDocs/OfficeDocs-SharePoint pull request #2936
Opened 2021-09-12 16:00 UTC by YuriySamorodov

2021-09-13 05:15 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-09-13 06:27 UTC, JohanFreelancer9 commented on OneDrive/list-onedrive-urls.md
>  After the script successfully completes, a text file is created in the location specified by the **$LogFile** variable in the script. This file contains a list of all OneDrive Urls in your organizati
```suggestion
After the script successfully completes, a text file is created in the location specified by the **$LogFile** variable in the script. This file contains a list of all OneDrive URLs in your organization. The following text provides an example of how the list of URLs in this file should be formatted.
```

2021-09-13 06:29 UTC, JohanFreelancer9 requested changes
Copy review - @YuriySamorodov, not related to this PR, but kindly commit the additional suggested change. Many thanks.

2021-09-13 06:50 UTC, JohanFreelancer9 approved these changes

2021-09-15 03:54 UTC, scanum commented
@kaarins PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-09-16 07:40 UTC, khayam123670 commented
Pull requests can only be merged by people who have write access to the [repository.](https://reviewscrush.com/)

2021-09-16 09:04 UTC, YuriySamorodov commented
Hi @scanum , could you please resolve conflicts here? Looks like I have to permission to do that.

2021-09-30 19:31 UTC, merged