Update viva-connections-overview.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #2947
Opened 2021-09-21 06:36 UTC by lindspea

https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2946
Fixed link

2021-09-22 02:07 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-09-22 03:32 UTC, JohanFreelancer9 approved these changes

2021-09-23 05:42 UTC, scanum commented
@LoreenLa PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-09-24 13:41 UTC, Holland-ODSP requested changes
This edit is not the message we want to send. We only want to inform people about the differences between two versions of Viva Connections. Viva Connections desktop (what's being references in this bullet) is not the version of Viva we want being to install. Therefore, the new label for the link is not approved.

2021-10-05 10:22 UTC, closed without merging