Update per-machine-installation.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3023
Opened 2021-10-28 09:25 UTC by baardhermansen

Tiny edit, only moved a full stop punctuation mark.

2021-11-01 01:39 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-01 03:46 UTC, JohanFreelancer9 commented on OneDrive/per-machine-installation.md
>  - All Windows versions supported by the sync app. [Learn more](https://support.office.com/article/cc0cb2b8-f446-445c-9b52-d3c2627d681e)
```suggestion
- All Windows versions supported by the sync app. [Learn more](https://support.office.com/article/cc0cb2b8-f446-445c-9b52-d3c2627d681e).
```

2021-11-01 03:47 UTC, JohanFreelancer9 requested changes
Copy review - @baardhermansen, one more minor additional edit, please. Many thanks.

2021-11-02 06:34 UTC, JohanFreelancer9 approved these changes

2021-11-03 02:29 UTC, scanum commented
@adeejoseph PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-03-04 16:15 UTC, merged