Update FSLogix min version and various links
MicrosoftDocs/OfficeDocs-SharePoint pull request #3031
Opened 2021-11-06 00:52 UTC by gacarini

2021-11-08 04:20 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-08 05:09 UTC, JohanFreelancer9 commented on OneDrive/sync-vdi-support.md
> +- Non-persistent virtual desktops that use [Azure Virtual Desktop](https://docs.microsoft.com/azure/virtual-desktop/).
```suggestion
- Non-persistent virtual desktops that use [Azure Virtual Desktop](/azure/virtual-desktop).
```

2021-11-08 05:10 UTC, JohanFreelancer9 commented on OneDrive/sync-vdi-support.md
> +- Non-persistent virtual desktops that have [FSLogix Apps](https://docs.microsoft.com/fslogix/configure-profile-container-tutorial) or [FSLogix Office Container](https://docs.microsoft.com/fslogix/co
```suggestion
- Non-persistent virtual desktops that have [FSLogix Apps](/fslogix/configure-profile-container-tutorial) or [FSLogix Office Container](/fslogix/configure-office-container-tutorial), and a Microsoft 365 subscription for all of the following operating systems:
```

2021-11-08 05:11 UTC, JohanFreelancer9 commented on OneDrive/sync-vdi-support.md
> +> The minimum supported versions are: OneDrive 19.174.0902.0013 and FSLogix Apps [2.9.7653.47581](https://docs.microsoft.com/fslogix/whats-new).
```suggestion
> The minimum supported versions are: OneDrive 19.174.0902.0013 and FSLogix Apps [2.9.7653.47581](/fslogix/whats-new).
```

2021-11-08 05:17 UTC, JohanFreelancer9 requested changes
Copy review - @gacarini, kindly commit my suggested changes to change the links to relative links. Many thanks.

2021-11-09 15:22 UTC, gacarini commented
@JohanFreelancer9  - I believe I applied all your suggestions.

2021-11-10 04:12 UTC, JohanFreelancer9 approved these changes

2021-11-10 05:15 UTC, scanum commented
@adeejoseph PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-15 16:52 UTC, merged