Fix resources link
MicrosoftDocs/OfficeDocs-SharePoint pull request #3055
Opened 2021-11-23 13:20 UTC by get-itips

The original link was a fasttrack resource link, it was then changed to a link that does not have the resources mentioned, so replacing it with a link to several template resources

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3051

2021-11-24 21:01 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-25 01:07 UTC, JohanFreelancer9 commented on migration/Fileshare-to-ODSP-migration-guide.md
> +- [Posters, email templates](https://www.microsoft.com/fasttrack/resources): Customizable templates to generate internal awareness and excitement.
```suggestion
- [Posters, email templates](https://www.microsoft.com/fasttrack/resources): Customizable templates to generate internal awareness and excitement
```

2021-11-25 01:08 UTC, JohanFreelancer9 requested changes
Copy review.

2021-11-25 13:07 UTC, JohanFreelancer9 approved these changes

2021-11-29 04:34 UTC, scanum commented
@JoanneHendrickson Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

2021-12-02 15:03 UTC, get-itips commented
@scanum can you help me get this merged? thanks

2022-01-06 22:26 UTC, get-itips commented
@tiburd tina can you help me with the merging?

2022-01-07 16:58 UTC, merged