Deprecation of org scoped promoted results in modern
MicrosoftDocs/OfficeDocs-SharePoint pull request #3060
Opened 2021-11-23 18:55 UTC by wobba

Added an important note to highlight that promoted results by query rules in modern for org scoped queries are being deprecated in December. Message center post MC293777 https://admin.microsoft.com/?&source=applauncher&ref=MessageCenter/:/messages/MC293777

2021-11-24 21:01 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-11-25 00:43 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-query-rules.md
> +> In December 2021 query rules with promoted results are deprecated for organization scoped queries in favor of [Bookmark and Q&A answers](https://docs.microsoft.com/en-us/microsoftsearch/manage-book
```suggestion
> In December 2021, query rules with promoted results are deprecated for organization scoped queries in favor of [Bookmark and Q&A answers](/microsoftsearch/manage-bookmarks) in modern search experiences. Examples of organization scoped queries are SharePoint Home and office.com. <p>Promoted results will continue to work for all classic search experiences and for sites and hub sites with modern search experiences until Bookmark answers are available for these scenarios. Promoted results will also continue to work for environments where Bookmark and Q&A answers are not available.
```

2021-11-25 00:48 UTC, JohanFreelancer9 requested changes
Copy review - @wobba, kindly commit the suggested changes. Many thanks.

2021-11-25 09:13 UTC, JohanFreelancer9 approved these changes

2021-11-29 04:35 UTC, scanum commented
@SerdarSoysal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

2021-11-30 14:20 UTC, merged