SPFx is not supposed to be used for branding
MicrosoftDocs/OfficeDocs-SharePoint pull request #3075
Opened 2021-12-02 19:28 UTC by westleyMS

The only thing supported by SPFx regarding branding is header/footer customizations.
If you try to change theme elements, you will have a flashing experience at the start of the page load where you see the OOB page, and then the SPFx stuff is added. This is not avoidable and is why we have no support for it. You might want to add more about the supported ways, here are some related links-
https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview
https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-branding

2021-12-06 04:53 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-06 08:13 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/branding-sharepoint-online-sites-modern-experience.md
> +|Use custom master pages and CSS that are ignored in the modern experience|Use the [SharePoint Framework](/sharepoint/dev/spfx/sharepoint-framework-overview) to add header and footer. Site templates
```suggestion
|Use custom master pages and CSS that are ignored in the modern experience|Use the [SharePoint Framework](/sharepoint/dev/spfx/sharepoint-framework-overview) to add headers and footers. Site templates and tenant settings offer some custom options|
```

2021-12-06 08:14 UTC, JohanFreelancer9 requested changes
Copy review - @westleyMS, kindly commit the minor suggested change. Many thanks.

2022-01-04 05:28 UTC, JohanFreelancer9 approved these changes

2022-04-18 13:32 UTC, MikePlumleyMSFT commented
@MattEEvans can you review this PR?

2022-04-18 22:13 UTC, merged