Update redirect-known-folders.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3082
Opened 2021-12-09 21:11 UTC by joshuc

2021-12-13 05:03 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2021-12-13 06:49 UTC, JohanFreelancer9 commented on OneDrive/redirect-known-folders.md
> +  > If Migration Manager will create the Documents, Pictures, or Desktop folders, ensure that Preserve file share permissions is not selected when performing the migration.
```suggestion
  > If Migration Manager will create the Documents, Pictures, or Desktop folders, ensure that **Preserve file share permissions** is not selected when performing the migration.
```

2021-12-13 06:49 UTC, JohanFreelancer9 requested changes
Copy review - @joshuc, kindly commit the suggested change. Many thanks.

2021-12-15 03:58 UTC, JohanFreelancer9 approved these changes

2021-12-15 07:00 UTC, scanum commented
@adeejoseph PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2021-12-15 19:20 UTC, adeejoseph approved these changes

2021-12-15 19:20 UTC, merged

2021-12-15 19:20 UTC, adeejoseph commented
Approved and merged.