update to announce impace of File Provider
MicrosoftDocs/OfficeDocs-SharePoint pull request #3111
Opened 2022-01-07 21:42 UTC by cartergreen

@gacarini

2022-01-10 04:37 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-10 04:56 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +> Beginning in macOS 12.1 Monterey Files On-Demand will be the default and there will not be a setting for users to turn it off.
```suggestion
> Beginning in macOS Monterey 12.1, Files On-Demand will be the default and there will not be a setting for users to turn it off.
```

2022-01-10 04:57 UTC, JohanFreelancer9 requested changes
Copy review - @cartergreen, kindly commit the suggested change. Many thanks.

2022-01-14 06:59 UTC, JohanFreelancer9 approved these changes

2022-01-17 06:05 UTC, scanum commented
@adeejoseph 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-18 04:37 UTC, merged