Suggest adding how to open migrated notebook
MicrosoftDocs/OfficeDocs-SharePoint pull request #3122
Opened 2022-01-19 14:59 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3116

2022-01-21 18:46 UTC, get-itips commented
@scanum

2022-01-22 00:47 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-22 04:46 UTC, JohanFreelancer9 commented on migration/migrate-onenote-spmt.md
> +For this **OneNote Notebook** to appear in your Notebooks list in OneNote, you can click the **Show Actions** ellipses, next to the notebook name in the Document library, then select **Open > Open in
```suggestion
For this **OneNote Notebook** to appear in your Notebooks list in OneNote, select the **Show Actions** ellipses next to the notebook name in the Document library, then select **Open > Open in app**. Remember to first close the OneNote application of the already migrated notebooks.
```

2022-01-22 04:47 UTC, JohanFreelancer9 requested changes
Copy review - suggestions.

2022-01-26 20:29 UTC, scanum approved these changes

2022-01-26 20:30 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-09 20:21 UTC, get-itips commented
@tiburd Can you help me getting this merged? Thank you

2022-02-09 21:34 UTC, merged