Include 2016 in Prerequisites
MicrosoftDocs/OfficeDocs-SharePoint pull request #3128
Opened 2022-01-24 17:27 UTC by MSGRRojas

:)

2022-01-26 20:29 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-27 06:08 UTC, JohanFreelancer9 commented on migration/overview-of-the-sharepoint-migration-assessment-tool.md
> +The tool is built to be run from within a SharePoint 2010, 2013 or 2016 farm and has these prerequisites:
```suggestion
The tool is built to be run from within a SharePoint 2010, 2013, or 2016 farm and has these prerequisites:
```

2022-01-27 06:09 UTC, JohanFreelancer9 requested changes
Copy review - @MSGRRojas, kindly commit the minor suggested change. Many thanks.

2022-01-31 08:17 UTC, JohanFreelancer9 approved these changes

2022-02-25 15:50 UTC, merged