Add a link to the related KB article
MicrosoftDocs/OfficeDocs-SharePoint pull request #3133
Opened 2022-01-27 16:07 UTC by PiotrekKrakowiak

Add a link to the KB article describing a scenario where search results are not available for the users who have permissions to see the content.

2022-01-30 22:50 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-01-31 07:57 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/make-site-content-searchable.md
> +> Please be aware that there are specific scenarios when the users have permissions to see the content but are still unable to find it in the search results. Refer to the article: https://docs.micros
```suggestion
> There are specific scenarios where users have permissions to see the content but are still unable to find it in the search results. For more details, see [Search results don't appear for group owners after creating a new Office 365 group](/sharepoint/troubleshoot/search/search-results-dont-appear-for-group-owners).
```

2022-01-31 07:58 UTC, JohanFreelancer9 requested changes
Copy review - @PiotrekKrakowiak, kindly commit the suggested changes. Many thanks.

2022-01-31 09:28 UTC, PiotrekKrakowiak commented
commiting changes

2022-01-31 10:16 UTC, JohanFreelancer9 approved these changes

2022-02-03 07:46 UTC, PiotrekKrakowiak commented
Hi Johan,

any idea when this will be published?

Thanks!
Piotrek

________________________________
From: JohanFreelancer9 ***@***.***>
Sent: 31 January 2022 11:16
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Piotrek ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Add a link to the related KB article (PR #3133)


@JohanFreelancer9 approved this pull request.

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/3133#pullrequestreview-867640511>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEEHJTZRJ5BKZ2A6FA2RJ63UYZOPXANCNFSM5M6LRICA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-02-07 01:11 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-09 16:58 UTC, PiotrekKrakowiak commented
I am a bit unsure where we are stuck here.... is there still anything that I need to click? 🙂 I have a customer impatiently waiting for this update....

Thanks!
Piotrek

________________________________
From: Manuela Scanu ***@***.***>
Sent: 07 February 2022 02:11
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Piotrek ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Add a link to the related KB article (PR #3133)


@SerdarSoysal<https://github.com/SerdarSoysal> PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

—
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/3133#issuecomment-1030972652>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEEHJT5ACK3WDKVYFE7OPO3UZ4L3RANCNFSM5M6LRICA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-02-14 22:23 UTC, merged