Update differences-classic-modern-search.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3148
Opened 2022-01-31 20:45 UTC by Josardi

Hi , Im Support Escalation Engineer for SharePoint Online at Microsoft, Recently i had a discussion with our PG due a customer was complaining about that Result sources were not working.

And PG said that once the tenant is fully in Microsoft Search , Custom result sources are not supported, and suggested use Microsoft Search Verticals

2022-02-07 01:10 UTC, scanum commented
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

2022-02-07 06:07 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/differences-classic-modern-search.md
> +For Example if your organization have Microsoft Search full deployed , Custom Result sources at site collection or tenant level won't affect the search result instead search admin can use Microsoft S
```suggestion
For example, if your organization has Microsoft Search full deployed, custom result sources at site collection or tenant level won't affect the search result. The search admin can use Microsoft search verticals instead. [Learn about Manage search verticals](https://docs.microsoft.com/en-us/microsoftsearch/manage-verticals).
```

2022-02-07 06:13 UTC, JohanFreelancer9 requested changes
Copy review - @Josardi, kindly commit the suggested changes. Many thanks.

2022-02-08 00:56 UTC, Josardi reviewed
Changes committed

2022-02-08 06:21 UTC, JohanFreelancer9 approved these changes

2022-02-08 14:04 UTC, Josardi commented
Hello @JohanFreelancer9  what are the next steps?

Thanks in advance

2022-02-12 00:22 UTC, scanum commented
@SerdarSoysal 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-02-16 19:25 UTC, merged