Update planning-hub-sites.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3168
Opened 2022-02-13 00:11 UTC by SusanHanley

Updated to clean up some terminology and add content about hub to hub associations

2022-02-19 20:36 UTC, SusanHanley commented
Not sure I did this correctly, but hoping these proposed changes make sense.

2022-02-21 23:15 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-02-24 12:10 UTC, MikePlumleyMSFT commented
@scanum, @JohanFreelancer9, following up on the copy edit.

2022-02-24 15:20 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/planning-hub-sites.md
> +|**Permissions** <br/> |Microsoft 365 group, plus SharePoint groups and permission levels  <br/> |SharePoint group  <br/> |Same as original site type. Hub sites do not alter an associated site's perm
```suggestion
|**Permissions** <br/> |Microsoft 365 group, plus SharePoint groups and permission levels  <br/> |SharePoint group  <br/> |Same as original site type. Hub sites do not alter an associated site's permissions - but you may add a "reader" group to the hub to make it easier to provide read access to associated sites. For more information, see: [Hub permissions](https://support.microsoft.com/office/set-up-your-sharepoint-hub-site-e2daed64-658c-4462-aeaf-7d1a92eba098#bkmk_managesiteassociationapprovals). <br/> |
```

2022-02-24 15:23 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/planning-hub-sites.md
> +> Association with a hub does not change the permissions on a site. If you associate a site that has restricted access with a hub, only users who have access to the restricted site will see content r
```suggestion
> Association with a hub does not change the permissions on a site. If you associate a site that has restricted access with a hub, only users who have access to the restricted site will see content rolled up on the hub. Information surfaced on the hub site is security trimmed: if you don't have access to the content, you won't see it. Something you may want to consider is adjusting permissions on the associated sites after you have assembled your hub family or [adding a hub "read" permission gorup to the hub](https://support.microsoft.com/office/set-up-your-sharepoint-hub-site-e2daed64-658c-4462-aeaf-7d1a92eba098#bkmk_managesiteassociationapprovals) and adding that permission group to associated sites. 
```

2022-02-24 15:25 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/planning-hub-sites.md
> +- **Do you want to add private or restricted access sites to the navigation?** Maybe. For example, HR may want to associate their private team site with the HR hub to make it more convenient for HR t
```suggestion
- **Do you want to add private or restricted access sites to the navigation?** Maybe. For example, HR may want to associate their private team site with the HR hub to make it more convenient for HR team members. But, the HR hub owner may not want to display a link to the HR team site in the shared navigation for the HR hub because this would make the private HR site more discoverable by everyone in the organization, who will get an access challenge when they click the link to the HR team site. If you add private sites to hub navigation, consider using [audience targeting](https://support.microsoft.com/office/target-navigation-news-files-links-and-web-parts-to-specific-audiences-33d84cb6-14ed-4e53-a426-74c38ea32293) so that the link only appears for members of the private site. In another scenario, there may be a site that is "semi-private" that you want interested people to discover. For example, you might have a community that wants to restrict membership to people with a specific expertise, but also wants to discover experts across the organization. In this scenario, users might get an access denied/request access message, but the site owner is prepared and wants to grant access to interested people. 
```

2022-02-24 15:26 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/planning-hub-sites.md
> +If you have only one hub, you'll miss the ability to easily surface related information in context and the ability to easily define a search scope for related content. For example, if you have a sing
```suggestion
If you have only one hub, you'll miss the ability to easily surface related information in context and the ability to easily define a search scope for related content. For example, if you have a single enterprise hub, it will be harder to surface just HR-related news on the HR site. Even small organizations may find that restricting the context in which users find information is helpful in managing information overload. We now have the ability to create a hierarchy of hubs to create [hub to hub associatons](/sharepoint/hub-to-hub-association). This allows you to create a network of hubs that roll-up to each other to create connections and additional search scopes. When hubs are associated with each other, content can be searched for and displayed on hubs up to three levels of association.
```

2022-02-24 15:28 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/planning-hub-sites.md
> +  - **Add hubs to global navigation**. Add your hubs to the global navigation for your tenant in the [SharePoint app bar](https://docs.microsoft.com/en-us/viva/connections/sharepoint-app-bar).
```suggestion
  - **Add hubs to global navigation**. Add your hubs to the global navigation for your tenant in the [SharePoint app bar](/viva/connections/sharepoint-app-bar). 
```

2022-02-24 15:33 UTC, JohanFreelancer9 requested changes
Copy review - @SusanHanley, kindly commit the suggested changes to change links to relative links and to remove the locale from the links. Many thanks.

2022-02-24 16:29 UTC, JohanFreelancer9 commented
@SusanHanley, thank you for committing the suggestions, but you seem to have missed the last one.

2022-02-24 18:38 UTC, SusanHanley commented
Sorry - missed that last one - mostly because I really don't know what I'm doing!! :-) Think I got it now!

2022-02-25 03:18 UTC, JohanFreelancer9 approved these changes

2022-02-25 12:40 UTC, MikePlumleyMSFT commented
Thanks for the updates @SusanHanley!

2022-02-25 12:40 UTC, merged