Rearranged Hub owners header
MicrosoftDocs/OfficeDocs-SharePoint pull request #3209
Opened 2022-03-10 13:36 UTC by MarvinBangert

Rearranged "Hub owners" from the text of "IT Admins" to new line and bold the beginning

2022-03-11 04:35 UTC, scanum commented
[@JohanFreelancer9](https://github.com/JohanFreelancer9) Copy editing is needed for this PR. Thanks.

2022-03-11 10:26 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/information-architecture-modern-experience.md
> +**Hub owners** – Hub owners manage hub-level content, branding, permissions, and navigational elements for hub in your organization’s intranet. Hub owners partner with departmental business owners an
```suggestion
**Hub owners** – Hub owners manage hub-level content, branding, permissions, and navigational elements for hubs in your organization’s intranet. Hub owners partner with departmental business owners and IT admins to [plan](./planning-hub-sites.md), create, and manage hubs throughout the lifecycle of your organization’s intranet architecture. 
```

2022-03-11 10:27 UTC, JohanFreelancer9 requested changes
Copy review - @MarvinBangert, kindly commit the minor additional suggested change. Many thanks.

2022-03-11 12:48 UTC, JohanFreelancer9 approved these changes

2022-03-14 04:30 UTC, scanum commented
@MattEEvans PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-04-18 13:41 UTC, merged