Updated license requirements.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3260
Opened 2022-04-22 19:23 UTC by nibandyo

Updated license requirements.

2022-04-22 19:25 UTC, nibandyo commented
Updated license requirements

2022-04-23 03:59 UTC, JohanFreelancer9 commented on OneDrive/limit-access.md
> +To access and use this feature, you organization must have one of the following subscriptions:
```suggestion
To access and use this feature, your organization must have one of the following subscriptions: 
```

2022-04-23 04:01 UTC, JohanFreelancer9 commented on OneDrive/limit-access.md
> +- Microsoft 365 E5 Compliance / A5 Compliance
```suggestion
- Office 365 E5/A5 
- Microsoft 365 E5/A5 
- Microsoft 365 E5 Compliance/A5 Compliance 
```

2022-04-23 04:01 UTC, JohanFreelancer9 requested changes
Copy review - @nibandyo, kindly commit the suggested changes. Many thanks.

2022-04-26 04:34 UTC, JohanFreelancer9 requested changes
@nibandyo, kindly also commit the suggested change to line 27 to correct the typo. Many thanks.

2022-04-26 04:43 UTC, nibandyo commented
Change updated

2022-04-26 06:12 UTC, JohanFreelancer9 approved these changes

2022-04-27 14:15 UTC, merged