Update control-access-from-unmanaged-devices.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3266
Opened 2022-05-02 22:07 UTC by SanjoyanM

We just added a new option and hence added one line in the documentation
`-ReadOnlyForUnmanagedDevices $false` Makes the entire site readonly for impacted users.

2022-05-03 11:45 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md
> + `-ReadOnlyForUnmanagedDevices $false` Makes the entire site readonly for impacted users.
```suggestion
 `-ReadOnlyForUnmanagedDevices $false` Makes the entire site read-only for impacted users. 
```

2022-05-03 11:45 UTC, JohanFreelancer9 requested changes
Copy review - @SanjoyanM, kindly commit the minor suggested change. Many thanks.

2022-05-04 08:49 UTC, JohanFreelancer9 approved these changes

2022-05-06 21:46 UTC, SanjoyanM commented
> @SanjoyanM is $false the correct setting? It seems like -ReadOnlyForUnmanagedDevices $true should make the site read-only.

@MikePlumleyMSFT You are right. fixing it.

2022-05-09 10:16 UTC, merged