Include Ad Hoc Step for OnPrem 2013
MicrosoftDocs/OfficeDocs-SharePoint pull request #3298
Opened 2022-05-25 20:33 UTC by cpaztrillo

2022-05-25 21:19 UTC, maxims1784 commented on SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md
> +2. If there are items in the App Domain field, leave them be, and it is empty, use localhost.
looks like **if** is missing, should it be 'and **if** it is empty'

2022-05-25 22:51 UTC, cpaztrillo commented on SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md
> +2. If there are items in the App Domain field, leave them be, and it is empty, use localhost.
Fixed.

2022-05-27 05:57 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md
> +The on-premises version of Sharepoint 2013 needs a hidden constraint in every federated query. The reverse proxy returns the documents indexed in the reverse proxy site itself, not the internal on-pr
```suggestion
The on-premises version of Sharepoint 2013 needs a hidden constraint in every federated query. The reverse proxy returns the documents indexed in the reverse proxy site itself, not the internal on-premise search site as expected. To avoid this, you need to execute the following steps in your Sharepoint 2013 on-premises admin site:
```

2022-05-27 05:58 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md
> +4. In the Permission Request XML field paste the following XML excerpt:
```suggestion
4. In the Permission Request XML field, paste the following XML excerpt:
```

2022-05-27 06:05 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md
> +5. The configuration page should look as in the screenshot below, finally, click on Create.
```suggestion
5. The configuration page should appear similar to the following screenshot. Finally, select **Create**.
```

2022-05-27 06:10 UTC, JohanFreelancer9 requested changes
Copy review - @cpaztrillo, kindly commit the suggested changes. Many thanks.

2022-05-27 15:07 UTC, JohanFreelancer9 approved these changes

2022-05-30 21:16 UTC, scanum commented
@SerdarSoysal PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-05-31 09:46 UTC, JohanFreelancer9 commented on SharePoint/SharePointServer/hybrid/configure-server-to-server-authentication.md
> +The on-premises version of Sharepoint 2013 needs a hidden constraint in every federated query. The reverse proxy returns the documents indexed in the reverse proxy site itself, not the internal on-pr
```suggestion
The on-premises version of SharePoint 2013 needs a hidden constraint in every federated query. The reverse proxy returns the documents indexed in the reverse proxy site itself, not the internal on-premise search site as expected. To avoid this, you need to execute the following steps in your SharePoint 2013 on-premises admin site:
```

2022-05-31 09:50 UTC, JohanFreelancer9 requested changes
@cpaztrillo, kindly commit the additional suggested changes. Many thanks.

2022-05-31 15:20 UTC, merged