Add Conversion of GSuite to O365
MicrosoftDocs/OfficeDocs-SharePoint pull request #3362
Opened 2022-07-08 17:32 UTC by MSGRRojas

2022-07-09 06:49 UTC, JohanFreelancer9 commented on migration/mm-faqs.md
> +Answer:  Yes.  When Migration Manager migrates the data from Google Workspace, the documents are converted to O365 format.
```suggestion
**Question:**  Can Migration Manager convert GSuite products to Office 365 products?
Answer:  Yes.  When Migration Manager migrates the data from Google Workspace, the documents are converted to Office 365 format.
```

2022-07-09 06:50 UTC, JohanFreelancer9 requested changes
Copy review - @MSGRRojas, kindly commit the suggested changes. Many thanks.

2022-07-09 14:10 UTC, JohanFreelancer9 approved these changes

2022-07-12 23:02 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-14 19:57 UTC, merged