Add EnableSyncAdminReports
MicrosoftDocs/OfficeDocs-SharePoint pull request #3383
Opened 2022-07-27 14:47 UTC by peterlewis

Add EnableSyncAdminReports as documented in https://docs.microsoft.com/en-us/onedrive/sync-health?tabs=macos

2022-07-28 06:45 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +If you enable this setting, OneDrive sync health reports will be sent to OneDrive sync health dashboard in the Microsoft 365 Apps Admin Center.
```suggestion
If you enable this setting, OneDrive sync health reports will be sent to OneDrive sync health dashboard in the Microsoft 365 Apps admin center.
```

2022-07-28 06:46 UTC, JohanFreelancer9 requested changes
Copy review - @peterlewis, kindly commit the minor suggested change. Many thanks.

2022-07-28 15:31 UTC, JohanFreelancer9 approved these changes

2022-07-30 04:36 UTC, scanum commented
@mkbond007 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-08-05 13:43 UTC, mkbond007 commented
@cartergreen Can you please review?

2022-11-07 13:55 UTC, MikePlumleyMSFT commented
Covered in [OneDrive sync reports in the Apps Admin Center](https://learn.microsoft.com/sharepoint/sync-health)

2022-11-07 13:55 UTC, closed without merging

2022-11-13 09:11 UTC, peterlewis commented
@MikePlumleyMSFT I appreciate it is covered in [OneDrive sync reports in the Apps Admin Center](https://learn.microsoft.com/sharepoint/sync-health), but given that the article contains a "[List of settings](https://learn.microsoft.com/en-us/sharepoint/deploy-and-configure-on-macos#list-of-settings)" I feel that it makes sense that the `EnableSyncAdminReports' setting should also be mentioned, even if it's just with a link to the aforementioned.

2022-11-29 12:41 UTC, MikePlumleyMSFT commented
I've added it to the related topics list at the bottom of the article.

2022-11-30 18:23 UTC, scanum commented
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.