Update viva-connections-desktop.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3409
Opened 2022-08-22 21:23 UTC by bpeterse03

2022-08-23 05:11 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/viva-connections-desktop.md
> +> - The [Viva Connections dashboard web part](https://docs.microsoft.com/viva/connections/use-dashboard-web-part-on-home-site) is not supported with the Viva Connections desktop (Only) app.
```suggestion
> - The [Viva Connections dashboard web part](/viva/connections/use-dashboard-web-part-on-home-site) is not supported with the Viva Connections desktop (only) app. 
```

2022-08-23 05:15 UTC, JohanFreelancer9 requested changes
Copy review - @bpeterse03, kindly commit the suggested changes. Many thanks.

2022-09-05 08:08 UTC, JohanFreelancer9 approved these changes

2022-09-12 08:12 UTC, scanum commented
@Holland-ODSP PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-12 14:49 UTC, Holland-ODSP approved these changes

2022-09-12 14:50 UTC, merged