Add T2T FAQ
MicrosoftDocs/OfficeDocs-SharePoint pull request #3419
Opened 2022-08-26 18:47 UTC by salarson

2022-08-29 03:17 UTC, JohanFreelancer9 commented on migration/mover-retirement-timeline.md
> +**Question:** Is Tenant to Tenant (T2T) migration supported in Migration Manager?</br>
```suggestion
**Question:** Is tenant-to-tenant migration supported in Migration Manager?</br>
```

2022-08-29 03:17 UTC, JohanFreelancer9 commented on migration/mover-retirement-timeline.md
> +**Answer:**  No. Microsoft will be offering a solution that will be available sometime in 2023. This will be a premium feature distinct from legacy Mover. In the interim, we recommend using a third-p
```suggestion
**Answer:**  No. Microsoft will be offering a solution that will be available sometime in 2023. This will be a premium feature distinct from legacy Mover. In the interim, we recommend using a third-party solution for your Microsoft 365 tenant-to-tenant migration needs.
```

2022-08-29 03:18 UTC, JohanFreelancer9 requested changes
Copy review - @salarson, kindly commit the suggested changes. Many thanks.

2022-08-29 06:36 UTC, JohanFreelancer9 approved these changes

2022-09-01 21:59 UTC, scanum commented
@JoanneHendrickson PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-09-01 23:16 UTC, tiburd commented on migration/mover-retirement-timeline.md
> +**Answer:**  No. Microsoft will be offering a solution that will be available sometime in 2023. This will be a premium feature distinct from legacy Mover. In the interim, we recommend using a third-p
```suggestion
**Answer:**  No. Microsoft is expecting to offer a solution sometime in 2023. The solution is expected to be a premium feature that's distinct from legacy Mover. In the interim, we recommend using a third-party solution for your Microsoft 365 tenant-to-tenant migration needs.
```

2022-09-01 23:20 UTC, tiburd commented on migration/mover-retirement-timeline.md
> +**Answer:**  No. Microsoft will be offering a solution that will be available sometime in 2023. This will be a premium feature distinct from legacy Mover. In the interim, we recommend using a third-p
My understanding is that Microsoft Docs does not publish definite dates or features of future releases.

2022-09-02 17:03 UTC, merged