Update option for hiding pre-release
MicrosoftDocs/OfficeDocs-SharePoint pull request #3444
Opened 2022-09-20 16:11 UTC by salarson

2022-09-21 07:21 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +> Example 'default write com.microsoft.OneDrive Tier -string "Deferred"'
```suggestion
> For example, `default write com.microsoft.OneDrive Tier -string "Deferred"`.                                                                      
```

2022-09-21 07:21 UTC, JohanFreelancer9 commented on OneDrive/deploy-and-configure-on-macos.md
> +
```suggestion
```

2022-09-21 07:22 UTC, JohanFreelancer9 requested changes
Copy review - @salarson, kindly commit the suggested changes. Many thanks.

2022-09-22 16:05 UTC, JohanFreelancer9 approved these changes

2022-09-26 03:28 UTC, scanum commented
@mkbond007 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-10-03 19:45 UTC, cartergreen commented
Both enterprise and deferred are supported here.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Mary-Katherine Bond ***@***.***>
Sent: Monday, October 3, 2022 11:42:19 AM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Carter Green ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Update option for hiding pre-release (PR #3444)


@cartergreen<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcartergreen&data=05%7C01%7CCarter.Green%40microsoft.com%7C9cf3577606b44fa106b108daa5776267%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638004229433196709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d4UZfGm5lTTXegj6LEOg5jdp0p2uwnBcUf%2B6lTvGndk%3D&reserved=0>
In this sentence being suggested, wouldn't they need to put "Enterprise"?
"For example, default write com.microsoft.OneDrive Tier -string "Deferred"."

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fpull%2F3444%23issuecomment-1265945042&data=05%7C01%7CCarter.Green%40microsoft.com%7C9cf3577606b44fa106b108daa5776267%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638004229433196709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O0DD9wYGjHnqOoUBSYy3xTFQR4QT4t7qfBvS0GnLMWE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKDUDZGZ4SQU77SLR2IGHVTWBMZJXANCNFSM6AAAAAAQRHNWJQ&data=05%7C01%7CCarter.Green%40microsoft.com%7C9cf3577606b44fa106b108daa5776267%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638004229433196709%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hlp4UBVc51jV5CD8pjsARaSojZ8vhl2TU%2Fb1DaDPwxs%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-03 19:47 UTC, merged