Adding a disclaimer about needing to update the settings for all regions
MicrosoftDocs/OfficeDocs-SharePoint pull request #3490
Opened 2022-10-19 22:50 UTC by TamineCM

Adding a disclaimer about needing to update the settings for all regions

2022-10-20 05:12 UTC, JohanFreelancer9 requested changes
Copy review - @TamineCM, kindly commit the suggested change. Many thanks.

2022-10-21 09:35 UTC, JohanFreelancer9 approved these changes

2022-10-24 05:01 UTC, scanum commented
@MikePlumleyMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-10-25 11:31 UTC, MikePlumleyMSFT commented
@TamineCM can you clarify what you mean by regions? Is this referring to Microsoft 365 Multi-Geo?

2022-11-03 20:44 UTC, merged