Clarify
MicrosoftDocs/OfficeDocs-SharePoint pull request #3505
Opened 2022-10-28 15:42 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3472

2022-10-31 09:14 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/api-access.md
> +    > Permissions of type delegated are added to the _SharePoint Online Client Extensibility Web Application Principal_ in Azure AD.
```suggestion
    > Permissions of type delegated are added to the _SharePoint Online Client Extensibility Web Application Principal_ in Azure AD.
    >
```

2022-10-31 09:14 UTC, JohanFreelancer9 requested changes
Copy review.

2022-11-01 12:02 UTC, JohanFreelancer9 approved these changes

2022-11-07 05:35 UTC, scanum commented
@lucabandMSFT PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2022-11-07 06:22 UTC, lucabandMSFT approved these changes
approved

2022-11-07 14:01 UTC, merged