Update doc
MicrosoftDocs/OfficeDocs-SharePoint pull request #3543
Opened 2022-12-06 14:54 UTC by catarinareis98m

Part of the support team reviewing the documentation

2022-12-07 12:57 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-query-suggestions.md
> +SharePoint has both a classic and a modern search experience, [learn about the differences between the classic and modern search experiences in SharePoint](differences-classic-modern-search.md). The
```suggestion
SharePoint has both a classic and a modern search experience, [learn about the differences between the classic and modern search experiences in SharePoint](differences-classic-modern-search.md). The modern search experience uses the same default result source as the classic search experience. Automatic query suggestions for the default result source appear only in the classic search experience.
```

2022-12-07 12:59 UTC, JohanFreelancer9 requested changes
Copy review - @catarinareis98m, kindly commit the minor additional change. Many thanks.

2022-12-12 20:43 UTC, wobba commented
@scanum does closing mean the change will be manually part of another branch update?

2023-01-12 17:22 UTC, scanum commented
Hi @wobba Hope all is doing well. Could youn please review the copy review and confirm the changes if you approve?

2023-01-13 07:45 UTC, JohanFreelancer9 approved these changes

2023-01-13 09:09 UTC, wobba commented
Looks good to me 👍

2023-01-18 00:27 UTC, scanum commented
@SerdarSoysal 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-01-20 21:02 UTC, merged