Update mm-get-started.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3554
Opened 2022-12-09 18:36 UTC by Leicham

clarifying some language

2022-12-10 08:53 UTC, JohanFreelancer9 commented on migration/mm-get-started.md
> +- **Setup migration agents.** Download and install a lightweight agent on each computer or virtual machine you want to connect to Migration Manager. The agent runs as a service and authenticates to b
```suggestion
- **Setup migration agents.** Download and install a lightweight agent on each computer or virtual machine you want to connect to Migration Manager. The agent runs as a service and authenticates to both your Microsoft 365 destination and your on-premises source.
```

2022-12-10 08:54 UTC, JohanFreelancer9 requested changes
Copy review - @Leicham, kindly commit the minor suggested change. Many thanks.

2022-12-12 06:32 UTC, JohanFreelancer9 approved these changes

2022-12-12 06:51 UTC, scanum commented
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-01-31 00:28 UTC, merged