Update mm-setup-clients.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3555
Opened 2022-12-09 19:04 UTC by Leicham

language updates and clarification

2022-12-10 09:22 UTC, JohanFreelancer9 commented on migration/mm-setup-clients.md
> +When migration file shares with Migration Manager, you first set up one or more "migration agents", by running a setup file on each computer or VM you choose to configure. Grouping provides agent fle
```suggestion
When migrating file shares with Migration Manager, you first set up one or more "migration agents", by running a setup file on each computer or VM you choose to configure. Grouping provides agent flexibility, such as only assigning particular migrations to a particular set of agents, or separating out agents in groups based on geographical location to optimize performance.
```

2022-12-10 09:22 UTC, JohanFreelancer9 commented on migration/mm-setup-clients.md
> +>**Multiple agents**.  If you have a large migration project and to set up multiple agents, we recommend that you download the agent setup file to a shared location. That way you can easily download
```suggestion
>**Multiple agents**.  If you have a large migration project and to set up multiple agents, we recommend that you download the agent setup file to a shared location. That way you can easily download the setup file on each computer or VM.  Multiple agents allow you to batch certain migrations jobs to particular groups depending on need. An example would be grouping agents by datacenter to achieve better performance based on geographical location. 
```

2022-12-10 09:22 UTC, JohanFreelancer9 commented on migration/mm-setup-clients.md
> +Example: You are migrating 10,000 users from on-premises shares in two datacenters to OneDrive. 2,000 users have data stored in a California datacenter and 8,000 users have data stored in a Vermont d
```suggestion
Example: You are migrating 10,000 users from on-premises shares in two datacenters to OneDrive. 2,000 users have data stored in a California datacenter and 8,000 users have data stored in a Vermont datacenter. You installed two agents at the California datacenter and six agents at the Vermont datacenter. By grouping the agents geographically, you could batch migrations where the source data is in California to the California agent group and for Vermont data to the Vermont agent group. Geographical grouping will provide performance benefits. Without grouping, all datacenters would be in a default group, and you would not have control over which agents are used. This could cause the California agents to migrate Vermont data and Vermont agents to migrate California data. While this technically will migrate files, performance could be affected.
```

2022-12-10 09:22 UTC, JohanFreelancer9 commented on migration/mm-setup-clients.md
> +Migration Manager automatically assigns tasks to a available agent. You cannot manually assign a task to a specific agent. Each agent can have up to 10 tasks in its queue. You can, however, assign ta
```suggestion
Migration Manager automatically assigns tasks to an available agent. You cannot manually assign a task to a specific agent. Each agent can have up to 10 tasks in its queue. You can, however, assign tasks to agent groups.
```

2022-12-10 09:23 UTC, JohanFreelancer9 requested changes
Copy review - @Leicham, kindly commit the suggested changes. Many thanks.

2022-12-12 06:25 UTC, JohanFreelancer9 approved these changes

2022-12-12 06:52 UTC, scanum commented
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-01-31 00:29 UTC, merged