Update Anyone Links Rollout
MicrosoftDocs/OfficeDocs-SharePoint pull request #3591
Opened 2023-01-25 22:41 UTC by salarson

2023-01-26 05:50 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/enable-file-requests.md
> +> Please note, if your tenant currently has Anyone Links enabled for SharePoint, we will be enabling this feature for SharePoint sites by default during the rollout. If you do not want File Requets t
```suggestion
>
> Note that if your tenant currently has Anyone Links enabled for SharePoint, we will be enabling this feature for SharePoint sites by default during the rollout. If you do not want File Requests to appear on SharePoint sites, you can opt out by running the following SharePoint Online management shell command: "Set-SPOTenant -CoreRequestFilesLinkEnabled $False".
```

2023-01-26 05:51 UTC, JohanFreelancer9 requested changes
Copy review - @salarson, kindly commit the suggested changes. Many thanks.

2023-01-27 04:28 UTC, JohanFreelancer9 approved these changes

2023-01-30 18:07 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-01-30 18:45 UTC, merged