added Microsoft 365 groups
MicrosoftDocs/OfficeDocs-SharePoint pull request #3596
Opened 2023-02-02 02:26 UTC by PramodBalusu

2023-02-02 07:17 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/change-site-address.md
> +The email address of the group will not be renamed. The group name is updated only if site name is updated during the rename process.
```suggestion
The email address of the group will not be renamed. The group name is updated only if the site name is updated during the rename process. 
```

2023-02-02 07:17 UTC, JohanFreelancer9 requested changes
Copy review - @PramodBalusu, kindly commit the minor suggested change. Many thanks.

2023-02-03 13:53 UTC, PramodBalusu commented
Please merge this PR

From: Manuela Scanu ***@***.***>
Sent: Thursday, February 2, 2023 9:37 PM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Pramod Kumar Balusu ***@***.***>; Assign ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] added Microsoft 365 groups (PR #3596)


Assigned #3596<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fpull%2F3596&data=05%7C01%7CPramod.Balusu%40microsoft.com%7C1f00c2cb267e45b72d9e08db058f8af9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638109886294780815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y47PVC4z6v1%2FqT9KE1f8Njq6LfPtAbCKtJT1lkwDVMQ%3D&reserved=0> to @PramodBalusu<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPramodBalusu&data=05%7C01%7CPramod.Balusu%40microsoft.com%7C1f00c2cb267e45b72d9e08db058f8af9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638109886294780815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=11lMZ3rLOqlMhMEWJowB6DkPXnGxwAy7eoCSjfI7pto%3D&reserved=0>.

-
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-SharePoint%2Fpull%2F3596%23event-8427457077&data=05%7C01%7CPramod.Balusu%40microsoft.com%7C1f00c2cb267e45b72d9e08db058f8af9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638109886294780815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gXgkTj7pQtPZ8tU5X1iebb%2FXMdS1jCYAzH0dgxWVTdo%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOMO5QG5QJAVZTDKC4O44DWVRVNFANCNFSM6AAAAAAUOORZEM&data=05%7C01%7CPramod.Balusu%40microsoft.com%7C1f00c2cb267e45b72d9e08db058f8af9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638109886294780815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wcumc2CVBlAnd5vLlJvfyfIH0qVy5nGIfynfLPH0F8c%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.******@***.***>>

2023-02-03 15:57 UTC, JohanFreelancer9 approved these changes

2023-02-24 10:57 UTC, peterouma reviewed
https://intranet.alxswe.com/corrections/10523815/correct

2023-10-02 04:48 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-02 11:48 UTC, merged