add example url
MicrosoftDocs/OfficeDocs-SharePoint pull request #3607
Opened 2023-02-07 23:04 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3579

2023-02-08 04:03 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/remove-search-results.md
> +4. On the **Remove Search Results** page, in the **URLs to remove** box, enter the URLs that you want to remove from the search results. For example, https://contoso.sharepoint.com/sites/site1, URLs
```suggestion
4. On the **Remove Search Results** page, in the **URLs to remove** box, enter the URLs that you want to remove from the search results, for example, https://contoso.sharepoint.com/sites/site1. URLs cannot contain a wildcard (\*) character. Enter one URL on each line. 
```

2023-02-08 04:03 UTC, JohanFreelancer9 requested changes
Copy review.

2023-02-09 04:43 UTC, JohanFreelancer9 approved these changes

2023-02-13 03:54 UTC, scanum commented
@SerdarSoysal 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-02-22 17:36 UTC, get-itips commented
@tiburd can you help me here? thanks

2023-02-23 16:17 UTC, merged