Update documentation regarding modern and classic search experiences
MicrosoftDocs/OfficeDocs-SharePoint pull request #3631
Opened 2023-02-16 13:03 UTC by wobba

Updated existing documentation to align with correct behavior.
Added new documentation related to deprecation of using a custom default result source in modern search where vertical admin is available.

2023-02-17 04:55 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/differences-classic-modern-search.md
> +- In environments where vertical configuration is available the modern search experience only shows results from the standard result source (Local SharePoint Results). To learn more, see [Manage sear
```suggestion
- In environments where vertical configuration is available the modern search experience only shows results from the standard result source (local SharePoint results). To learn more, see [Manage search verticals](/microsoftsearch/manage-verticals).
```

2023-02-17 04:55 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-query-rules.md
> +SharePoint has both a classic and a modern search experience. Only query rules that return promoted results can affect the modern search experience. Query rules which do query re-writes are not suppo
```suggestion
SharePoint has both a classic and a modern search experience. Only query rules that return promoted results can affect the modern search experience. Query rules which do query rewrites are not supported for modern experiences. Users might see such promoted results on the **All** tab on the search results page when they search across all of SharePoint. [Learn more about the differences between the classic and modern search experiences in SharePoint](differences-classic-modern-search.md).
```

2023-02-17 04:55 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/manage-query-rules.md
> +> In December 2021, query rules with promoted results are deprecated for organization scoped queries in favor of [Bookmark and Q&A answers](/microsoftsearch/manage-bookmarks) in modern search experie
```suggestion
> In December 2021, query rules with promoted results were deprecated for organization-scoped queries in favor of [Bookmark and Q&A answers](/microsoftsearch/manage-bookmarks) in modern search experiences. Examples of organization-scoped queries are SharePoint Home and Office.com. <p>Promoted results will continue to work for all classic search experiences and for sites and hub sites with modern search experiences. Promoted results will also continue to work for environments where Bookmark and Q&A answers are not available.
```

2023-02-17 04:57 UTC, JohanFreelancer9 requested changes
Copy review - @wobba, kindly commit the minor unrelated changes. Many thanks.

2023-02-17 09:08 UTC, wobba commented on SharePoint/SharePointOnline/differences-classic-modern-search.md
> +- In environments where vertical configuration is available the modern search experience only shows results from the standard result source (Local SharePoint Results). To learn more, see [Manage sear
The source is named "Local SharePoint Results" in all UI's, hence the capital letters per word.

2023-02-17 13:50 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/differences-classic-modern-search.md
> +- In environments where vertical configuration is available the modern search experience only shows results from the standard result source (Local SharePoint Results). To learn more, see [Manage sear
@wobba, thank you for the explanation. Let's leave it as is. Could you please mark the suggestion as "Resolved"? Thanks again.

2023-02-17 13:50 UTC, JohanFreelancer9 approved these changes

2023-02-19 19:22 UTC, scanum commented
@SerdarSoysal 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-03 07:47 UTC, wobba commented
@SerdarSoysal @scanum What's the progress of merging this as I need it updated before a message center post goes out.

2023-03-08 02:50 UTC, scanum commented
@tiburd Hi Tina! Hope all is well. Is this something you can help us with? Thank you!

2023-03-08 15:06 UTC, tiburd commented
@wobba 
Hi, Mikael,

As a Microsoft-internal submitter, we recommend you submit changes via private repositories, as described in [the authoring guide](https://review.docs.microsoft.com/en-us/Office-Authoring-Guide/office-docs-authoring-overview?branch=main).

We're closing this pull request (PR). 

Please resubmit your proposed changes via the SharePoint private repo, and note that your branch should merge with main instead of public.

Thank you!

cc: @scanum

2023-03-08 15:06 UTC, closed without merging

2023-03-08 16:59 UTC, tiburd commented
@wobba 
Thank you - sincere apologies for the delay in providing the feedback.