Update control-lists.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3679
Opened 2023-03-06 21:39 UTC by sunar91

PM working on Lists - approvals integration: We are introducing two new list templates with Approvals app integration and added them to the list here.

2023-03-07 07:54 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/control-lists.md
> +- Content Scheduler with Approvals: 'C381BD64-C1A1-4D9E-BE9C-0571900FF1CE'
```suggestion
- Travel requests with approvals: '4EB20749-6360-417C-83DD-06135C0FF1CE'
- Content scheduler with approvals: 'C381BD64-C1A1-4D9E-BE9C-0571900FF1CE'
```

2023-03-07 07:55 UTC, JohanFreelancer9 requested changes
Copy review - @sunar91, kindly commit the suggested changes. Many thanks.

2023-03-07 11:47 UTC, JohanFreelancer9 approved these changes

2023-03-08 02:44 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-03-08 12:05 UTC, merged