Update block-download-from-sites.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3758
Opened 2023-03-30 19:50 UTC by SanjoyanM

2023-03-31 20:19 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/block-download-from-sites.md
> +    For example, `Set-SPOSite -Identity https://contoso.sharepoint.com/sites/research -BlockDownloadPolicy $true`. You can apply this cmdlet to OneDrives as well by changing the url like `https://con
```suggestion
    For example, `Set-SPOSite -Identity https://contoso.sharepoint.com/sites/research -BlockDownloadPolicy $true`. You can apply this cmdlet to OneDrives as well by changing the URL to `https://contoso-my.sharepoint.com/personal/John`. 
```

2023-03-31 20:20 UTC, JohanFreelancer9 requested changes
Copy review - @SanjoyanM, kindly commit the suggested change. Many thanks.

2023-04-07 05:19 UTC, JohanFreelancer9 approved these changes

2023-10-02 04:51 UTC, scanum commented
@MachelleTranMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-10-05 23:10 UTC, merged