Update hub-to-hub-association.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #3771
Opened 2023-04-04 14:37 UTC by Marweis

Added note:  Web parts configured to show content from all sites in the hub, will continue to show data from the original parent hub only

2023-04-04 19:17 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/hub-to-hub-association.md
> +> - Web parts configured to show content from all sites in the hub, will continue to show data from the original parent hub only
```suggestion
> - Web parts configured to show content from all sites in the hub will continue to show data from the original parent hub only.
```

2023-04-04 19:18 UTC, JohanFreelancer9 requested changes
Copy review - @Marweis, kindly commit the suggested changes. Many thanks.

2023-04-04 19:28 UTC, Marweis commented
@JohanFreelancer9 - committed suggestions. Please publish.

2023-04-05 19:40 UTC, JohanFreelancer9 approved these changes

2023-04-10 03:19 UTC, scanum commented
@MattEEvans 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-17 20:22 UTC, MattEEvans approved these changes
Looks good. Thanks.

2023-04-17 20:25 UTC, merged