added details about reset to 5TB
MicrosoftDocs/OfficeDocs-SharePoint pull request #3793
Opened 2023-04-14 16:25 UTC by PramodBalusu

2023-04-16 14:54 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/change-user-storage.md
> +- When a user has filled their 5 TB of OneDrive storage to at least 90% capacity, Microsoft will increase your default storage space in OneDrive to up to 25 TB per user (admins may set a lower per-us
```suggestion
- When a user has filled their 5 TB of OneDrive storage to at least 90% capacity, Microsoft will increase your default storage space in OneDrive to up to 25 TB per user (admins may set a lower per-user limit if they want to). The storage limit will be reset to 5 TB if OneDrive storage utilization drops below 90% of the 5 TB capacity.
```

2023-04-16 14:55 UTC, JohanFreelancer9 requested changes
Copy review - @PramodBalusu, Kindly commit the suggested change. Many thanks.

2023-04-17 15:30 UTC, JohanFreelancer9 approved these changes

2023-04-24 16:24 UTC, PramodBalusu commented
@JohanFreelancer9  any reason why this is still in open state and changes were not merged to public

2023-04-25 02:19 UTC, JohanFreelancer9 commented
> @JohanFreelancer9 any reason why this is still in open state and changes were not merged to public

@scanum

2023-04-27 03:42 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-04-27 10:21 UTC, merged