Edit format consistency
MicrosoftDocs/OfficeDocs-SharePoint pull request #3850
Opened 2023-05-23 00:39 UTC by helloiamcait

Added "." after each step for consistency.

2023-05-23 10:53 UTC, JohanFreelancer9 approved these changes

2023-05-28 18:04 UTC, scanum commented
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-05-29 13:49 UTC, JohanFreelancer9 commented on migration/mm-google-overview.md
> +- **Step 6:** [Migrate and Monitor](mm-google-step6-migrate-monitor.md). After reviewing your migration setup, migrate your Google accounts and monitor the progress
```suggestion
- **Step 6:** [Migrate and Monitor](mm-google-step6-migrate-monitor.md). After reviewing your migration setup, migrate your Google accounts and monitor the progress.
```

2023-05-29 13:51 UTC, JohanFreelancer9 requested changes
Apologies @helloiamcait, could you please commit the additional suggested change? Many thanks.

2023-05-30 19:34 UTC, helloiamcait commented
> Apologies @helloiamcait, could you please commit the additional suggested change? Many thanks.

Absolutely! I've committed the suggested change. Thanks!

2023-06-05 04:32 UTC, scanum commented
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-08-30 23:24 UTC, merged