Add Cond Access info
MicrosoftDocs/OfficeDocs-SharePoint pull request #3854
Opened 2023-05-30 17:35 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3849

2023-05-31 05:46 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/allow-syncing-only-on-specific-domains.md
> +   > This setting is only applicable to Active Directory domains. It does not apply to Azure AD domains. If you have devices which are only Azure AD joined, consider using a [Conditional Access Polic
```suggestion
   > This setting is only applicable to Active Directory domains. It does not apply to Azure AD domains. If you have devices that are only Azure AD joined, consider using a [Conditional Access Policy](/azure/active-directory/conditional-access/overview) instead, For details, see [Enable conditional access support in the OneDrive sync app](enable-conditional-access.md).
```

2023-05-31 05:46 UTC, JohanFreelancer9 requested changes
Copy review.

2023-05-31 13:30 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/allow-syncing-only-on-specific-domains.md
> +   > This setting is only applicable to Active Directory domains. It does not apply to Azure AD domains. If you have devices that are only Azure AD joined, consider using a [Conditional Access Policy
```suggestion
   > This setting is only applicable to Active Directory domains. It does not apply to Azure AD domains. If you have devices that are only Azure AD joined, consider using a [Conditional Access Policy](/azure/active-directory/conditional-access/overview) instead. For details, see [Enable conditional access support in the OneDrive sync app](enable-conditional-access.md).
```

2023-05-31 13:33 UTC, JohanFreelancer9 requested changes
Copy review, apologies @get-itips, one more

2023-05-31 15:17 UTC, JohanFreelancer9 approved these changes

2023-06-02 03:41 UTC, scanum commented
@MikePlumleyMSFt
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-02 11:38 UTC, merged