Clarify API Access permissions
MicrosoftDocs/OfficeDocs-SharePoint pull request #3873
Opened 2023-06-09 17:07 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/3858

2023-06-10 06:27 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sharepoint-admin-role.md
> +> To manage API access in the SharePoint admin center, the application administrator role or the Global Administrator role might be required, for more information, see [Manage access to Azure AD-secu
```suggestion
> To manage API access in the SharePoint admin center, the application administrator role or the Global administrator role might be required. For more information, see [Manage access to Azure AD-secured APIs](api-access.md).
```

2023-06-10 06:27 UTC, JohanFreelancer9 requested changes
Copy review.

2023-06-12 13:37 UTC, JohanFreelancer9 approved these changes

2023-06-14 20:26 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-06-14 20:45 UTC, merged