OneDrive Sync Agent Health Report Changes
MicrosoftDocs/OfficeDocs-SharePoint pull request #3998
Opened 2023-08-11 10:44 UTC by maurice-daly

Updated the documentation to advise the old sync agent health setting has been retired, and included instructions as to how to set this in Intune.

2023-08-17 07:17 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +> **You must enable this setting on the devices from which you want to get reports using one of the below methods.** This setting does not affect users. We recommend a gradual rollout starting with a
```suggestion
> **You must enable this setting on the devices from which you want to get reports using one of the following methods.** This setting does not affect users. We recommend a gradual rollout starting with a few test devices per day, then up to 100 devices per day, then gradually up to 10,000 devices per day until you are done.
```

2023-08-17 07:17 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +    b. Right-click > **New** > **DWORD (32-bit) Value**
```suggestion
    b. **Right-click** > **New** > **DWORD (32-bit) Value**
```

2023-08-17 07:17 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +- Select **Enabled** and then press **OK**.
```suggestion
- Select **Enabled** and then select **OK**.
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Go to [Microsoft Intune Admin Center](https://intune.microsoft.com) and sign in as a global admin, Intune admin role, or an account with sufficient RBAC permissions.
```suggestion
-  Go to [Microsoft Intune Admin Center](https://intune.microsoft.com) and sign in as a global admin, Intune admin, or an account with sufficient RBAC permissions.
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Click on Devices, Windows, and then click on "Configuration profiles".
```suggestion
-  Select **Devices** > **Windows**, and then select **Configuration profiles**.
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  If creating a new profile, provide a name for the profile and go to the Configuration settings tab. If editing a profile, you will by default go direct to the Configuration settings tab.
```suggestion
-  If creating a new profile, provide a name for the profile and go to the Configuration settings tab. If editing a profile, you will by default go directly to the Configuration settings tab.
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Click on "Add setting" and the Settings picker will be displayed on the right side of the UI.
```suggestion
-  Select **Add setting** and the Settings picker will be displayed on the right side of the UI.
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Close the Settings picker from the "X" at the top right.
```suggestion
-  Close the Settings picker from the **X** at the top right.
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +    b. Right-click > **New** > **DWORD (32-bit) Value**
```suggestion
    b. **Right-click** > **New** > **DWORD (32-bit) Value**
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +To apply the setting on a single PC, follow these steps:
```suggestion
To apply the setting on a single device, follow these steps:
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +- Select **Enabled** and then press **OK**.
```suggestion
- Select **Enabled** and then select **OK**.
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Go to [Microsoft Intune Admin Center](https://intune.microsoft.com) and sign in as a global admin, Intune admin role, or an account with sufficient RBAC permissions.
```suggestion
-  Go to [Microsoft Intune Admin Center](https://intune.microsoft.com) and sign in as a global admin, Intune admin, or an account with sufficient RBAC permissions.
```

2023-08-17 07:18 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Click on Devices, Windows, and then click on "Configuration profiles".
```suggestion
-  Select **Devices** > **Windows**, and then select **Configuration profiles**.
```

2023-08-17 07:19 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  If creating a new profile, provide a name for the profile and go to the Configuration settings tab. If editing a profile, you will by default go direct to the Configuration settings tab.
```suggestion
-  If creating a new profile, provide a name for the profile and go to the Configuration settings tab. If editing a profile, you will by default go directly to the Configuration settings tab.
```

2023-08-17 07:19 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Click on "Add setting" and the Settings picker will be displayed on the right side of the UI.
```suggestion
-  Select **Add setting** and the Settings picker will be displayed on the right side of the UI.
```

2023-08-17 07:19 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Close the Settings picker from the "X" at the top right.
```suggestion
-  Close the Settings picker from the **X** at the top right.
```

2023-08-17 07:19 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  Click on the toggle switch to set "Enable sync health reporting for OneDrive" to "Enabled".
```suggestion
-  Select the toggle switch to set "Enable sync health reporting for OneDrive" to **Enabled**.
```

2023-08-17 07:19 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +-  If creating a new profile, continue through the wizard, assing scope tags if required, and assigning the profile as required. If you are editing the profile, click on the "Review + save" button.
```suggestion
-  If creating a new profile, continue through the step-by-step guide, assigning scope tags if required, and assigning the profile as required. If you are editing the profile, select **Review + save**.
```

2023-08-17 07:21 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/sync-health.md
> +=======
```suggestion
```

2023-08-17 07:22 UTC, JohanFreelancer9 requested changes
Copy review - @maurice-daly, kindly commit the suggested changes. Many thanks.

2023-08-17 14:32 UTC, JohanFreelancer9 approved these changes

2023-08-25 07:24 UTC, maurice-daly commented
Just checking in for an approval on the pull request.

2023-08-26 05:40 UTC, JohanFreelancer9 commented
> Just checking in for an approval on the pull request.

@scanum

2023-08-31 20:09 UTC, maurice-daly commented
Just another push on the commit.

2023-09-01 06:13 UTC, scanum commented
@MikePlumleyMSFT 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-09-05 13:10 UTC, MikePlumleyMSFT commented
@maurice-daly there's another update in the queue to clarify that the he old sync agent health setting has been retired. Intune is documented separately. We wouldn't include that here.

2023-09-05 13:10 UTC, closed without merging