Fix typos
MicrosoftDocs/OfficeDocs-SharePoint pull request #4076
Opened 2023-10-13 19:31 UTC by get-itips

closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/4062

2023-10-14 06:05 UTC, JohanFreelancer9 commented on migration/mm-box-step5-map-identities.md
>  Upload your own users and groups mappings using the M
```suggestion
Upload your own users and groups mappings using the M.
```

2023-10-14 06:06 UTC, JohanFreelancer9 requested changes
@get-itips, minor additional edit, please.

2023-10-17 11:24 UTC, JohanFreelancer9 approved these changes

2023-10-18 19:36 UTC, get-itips commented
@JoanneHendrickson

2023-10-19 02:51 UTC, scanum commented
@JoanneHendrickson 
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-12-14 16:43 UTC, merged