Update onedrive-office-hours.md
MicrosoftDocs/OfficeDocs-SharePoint pull request #4097
Opened 2023-11-14 18:32 UTC by bigburrito21

removed terms like support and customer so that this article is not the top search result for "OneDrive customer support"

2023-11-15 05:26 UTC, JohanFreelancer9 commented on SharePoint/SharePointOnline/onedrive-office-hours.md
> +**You may opt out of OneDrive office hours at anytime**
```suggestion
**You may opt out of OneDrive office hours at any time.**
```

2023-11-15 05:27 UTC, JohanFreelancer9 requested changes
Copy review - @bigburrito21, kindly commit the minor additional suggested change. Many thanks.

2023-11-15 19:21 UTC, bigburrito21 commented
Done

From: JohanFreelancer9 ***@***.***>
Sent: Tuesday, November 14, 2023 9:28 PM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Paul Diamond (MODERN WORK) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Update onedrive-office-hours.md (PR #4097)


@JohanFreelancer9 requested changes on this pull request.

Copy review - @bigburrito21<https://github.com/bigburrito21>, kindly commit the minor additional suggested change. Many thanks.

-
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/4097#pullrequestreview-1731265065>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5SYYNJRFQXZIZ4ENH4HVL3YERHGJAVCNFSM6AAAAAA7LIKK3WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZRGI3DKMBWGU>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-11-16 06:31 UTC, JohanFreelancer9 approved these changes

2023-11-16 19:43 UTC, bigburrito21 commented
Do you know when the article changes will be published?
Microsoft OneDrive customer office hours - SharePoint in Microsoft 365 | Microsoft Learn<https://learn.microsoft.com/en-us/sharepoint/onedrive-office-hours>

From: JohanFreelancer9 ***@***.***>
Sent: Wednesday, November 15, 2023 10:32 PM
To: MicrosoftDocs/OfficeDocs-SharePoint ***@***.***>
Cc: Paul Diamond (MODERN WORK) ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/OfficeDocs-SharePoint] Update onedrive-office-hours.md (PR #4097)


@JohanFreelancer9 approved this pull request.

-
Reply to this email directly, view it on GitHub<https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/pull/4097#pullrequestreview-1733596866>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5SYYNOKBKVAP2ZN3QMDVY3YEWXNVAVCNFSM6AAAAAA7LIKK3WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZTGU4TMOBWGY>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-11-17 00:27 UTC, scanum commented
@MikePlumleyMSFT
PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

2023-11-17 11:43 UTC, merged